### ISSUE TITLE
Zitieren Bilder Onlinequellen

### ISSUE THREAD

**Issue by thesolution90** [andygrunwald/FOM-LaTeX-Template#106]
Hallo zusammen,

erstmal vielen Dank Andy and allen Contributors für eure Arbeit hier. Die Vorlage ist echt klasse! :)
Das Zitieren bzw Angeben von Online Bilderquellen ist mir nicht klar. Wie mache ich das am besten? Lt. http://www.zitieren.de/zitieren/bilder-und-grafiken-zitieren/ müsste ja dann die Quelle im Abbildungsverzeichnis stehen. Bei mir wären Datum und Uhrzeit auch sehr wichtig, da es sich um Grafiken mit kontinuierlicher Zeitachse handelt.

Vielen Dank und Grüße
Christopher

**Comment by SimonHaak** [comment]
Moin,
an deiner Stelle würde ich mich eher an den Leitfaden der FOM, als an die angegebene Webseite halten. Die Dozenten halten es zwar alle unterschiedlich, aber ich würde es da eher mit Seite 12 des Leitfadens halten und die Quelle ganz normal in das Literaturverzeichnis schreiben. Du könntest also zum Beispiel die \footcite{} Funktion verwenden.

Auf Seite 44 des Leitfadens ist eine Beispieldarstellung. Da wird (warum auch immer, gefällt mir persönlich überhaupt nicht) erst der Titel der Abbildung, dann die Abbildung und zuletzt die Quelle (nicht in der Fußnote) angegeben.
Die Darstellung aus dem Leitfaden solltest du z.B. so erreichen können:

> \captionsetup{font=bf, labelfont=bf}
> \begin{figure}[H]
>     \begin{center}
>     \caption{Verzeichnisstruktur der \LaTeX{}-Dateien}
>     \includegraphics[width=0.9\textwidth]{verzeichnisStruktur}
>     \\\\
>     \cite[Quelle: ][]{Balzert.2008}
>     \end{center}
> \end{figure}

Alternativ müsste man auch \footcite irgendwie in die caption einbauen können. Ich persönlich finde es einheitlich (=Quellenangabe immer in der Fußnote) schöner.

Hoffe das hilft dir weiter.

**Comment by thesolution90** [comment]
Danke für die Antwort. Hat mir sehr weitergeholfen. Jetzt muss nur noch die Note stimmen :)
