### ISSUE TITLE
Buch mit 3 und mehr Autoren

### ISSUE THREAD

**Issue by xremix** [andygrunwald/FOM-LaTeX-Template#109]
Derzeit kann die aktuelle Vorlage wohl nur maximal 2 Autoren pro Buch. Bei mehr Autoren wird einfach die ID der Literatur in der Fußnote ausgegeben.

Weiß jemand vielleicht zufällig wie man das Problem behebt?

**Comment by SimonHaak** [comment]
Moin,
das müsste als Setting im Biblatex style einstellbar sein. 
Wie genau machst du die Fußnote und was steht in deiner Literatur.bib Datei für das Buch?

Nächste Woche kann ich mir das gerne genauer anschauen. Sollte es dringender sein nimm am besten den Style für den alten Leitfaden und frag deinen Dozenten ob der auch geht.

**Comment by xremix** [comment]
Vielen Dank für deine schnelle Antwort @SimonHaak ! Da werde ich noch mal schauen.

In meiner `Literatur.bib` habe ich z.B. das folgende Beispiel:
```
@book{Kaiser.2018,
 author = {Kaiser, Markus und Buttkereit, Aline-Florence und Hagenauer, Johanna},
 year = {2018},
 title = {Journalistische Praxis: Chatbots},
 address = {München},
 publisher = {Springer VS}
}
```

Das Zitat selbst sieht dann so aus:

`\footcite[Vgl. ][S. 5 f.]{Kaiser.2018}``

In der PDF steht in der Fußnote dann nur fett **Kaiser.2018**
Wäre klasse, falls Du dazu noch etwas finden würdest.

**Comment by xremix** [comment]
@SimonHaak beim erstellen der PDF Datei über Docker erhalte ich den folgenden Fehler:

`fom_1  | WARN - Name "Kaiser, Markus und Buttkereit, Aline-Florence und Hagenauer, Johanna" has too many commas: skipping name`

Interessanterweise bringt es auch keine Besserung, wenn ich in der `thesis_main.tex `maxcitenames=4,` einstelle. 



Im Internet habe ich noch die Empfehlung gelesen den Authoren wie folgt ab zu ändern:
`author = {Markus Kaiser und Aline-Florence Buttkereit und Johanna Hagenauer},`

In diesem Fall funktioniert zwar das erstellen der PDF Datei, aber ein Author wird einfach abgeschnitetn und es dabei auch kein et. al. hinzugefügt:
`6 Vgl. Aline-Florence Buttkereit und Johanna Hagenauer, 2018, S. 5 f.`

**Comment by xremix** [comment]
Ich konnte das Problem lösen... war eigentlich ganz trivial:
```
// Funktioniert Nicht
 author = {Kaiser, Markus und Buttkereit, Aline-Florence und Hagenauer, Johanna},
// Funktioniert
author = {Kaiser, Markus and Buttkereit, Aline-Florence and Hagenauer, Johanna},
```
