### ISSUE TITLE
Welcome @ChristianLuxem

### ISSUE THREAD

**Issue by andygrunwald** [andygrunwald/FOM-LaTeX-Template#111]
I want to share some news with you:
Since today @ChristianLuxem has joined the project as an official collaborator.

Christian is working with this template for quite some time already and is actively shaping Pull Requests with his feedback. He helps a lot. He will help us to drive this forward. Thank you for joining and happy collaborating!

If you see Christian in an issue, say hi (or use this issue) :)

🍻 

PS: We will close this issue after "some" time - Just to share the news.

**Comment by xremix** [comment]
This is great! Looking forward to having this continued!
