### ISSUE TITLE
Auführen der compile.sh und integration mit VS Code

### ISSUE THREAD

**Issue by patm80** [andygrunwald/FOM-LaTeX-Template#114]
Hallo zusammen,

erst mal vielen Dank für das coole Template! Damit bin ich guter Dinge, dass ich Latex für mich auch endlich mal benutzen kann. Ich habe MacTex auf meinem MacBook installiert. Ich benötige zum Ausführen der compile.sh allerdings immer sudo Rechte, damit die Kompilierung erfolgreich durch läuft. Ist das normal so oder sollte die compile.sh ohne sudo Rechte ausführbar sein?

Darüber hinaus würde ich gerne wie in der README beschrieben dieses Template mit VS Code nutzen. Ich habe dabei bereits meine settings.json entsprechend der im Projekt vorhandenen settings.json angepasst. Wenn ich allerdings über VS Code versuche zu kompilieren kommt er nicht mal über den ersten Schritt hinaus.
Ich vermute, dass die beiden Punkte zusammenhängen und VS Code nicht genügend Rechte besitzt zu kompilieren. Dann wäre meine Frage wie ich am einfachsten MacTex auf User-Ebene installiere...

Viele Grüße,
Patrick

**Comment by patm80** [comment]
Hallo noch mal,

als kurze Info: Ersteres konnte ich jetzt lösen, indem ich die Owner für Latex angepasst habe. Ich kann das Script jetzt ohne Sudo Rechte ausführen.
Das Kompilieren über VS Code geht aber leider weiterhin nicht.
Muss ich da noch etwas beachten, abgesehen von den settings.json Einstellungen?

Gruß,
Patrick

**Comment by ChristianLuxem** [comment]
Hallo Patrick,

warum nutzt du nicht das kompilieren über Docker? Damit wirst du diese Probleme alle übergehen, probier es dochmal aus :)

**Comment by patm80** [comment]
Hey Christian,

danke für die schnelle Antwort! Dann werde ich das direkt mal ausprobieren :)
Bin schon mal froh, dass immerhin das Script soweit funktioniert.

Danke und viele Grüße,
Patrick

**Comment by patm80** [comment]
Hey Christian,

vielen Dank für den Tipp, hat sofort geklappt! Das ist wirklich sehr unproblematisch! :)
Jetzt kann ich endlich anfangen das Template anzupassen!

Ich würde das Issue hiermit auch schließen.

Vielen Dank und viele Grüße,
Patrick
