### ISSUE TITLE
Latex Paket hinzufügen

### ISSUE THREAD

**Issue by patm80** [andygrunwald/FOM-LaTeX-Template#115]
Hallo zusammen,

ich muss aktuell mein Expose vorbereitend für meine Thesis schreiben und muss dabei einerseits meine Literaturrecherche angeben und die für das Expose verwendete Literatur. Dementsprechend brauche ich zwei Literaturverzeichnisse ... Nach etwas Recherche stieß ich auf das Paket 'multibbl'. Das kann ich so einfach leider nicht hinzufügen und bekomme die Fehlermeldung "! Package biblatex Error: Incompatible package 'multibbl'." beim kompilieren.

Meine Frage wäre jetzt einmal, ob es möglich ist Pakete nach zu installieren? In meiner lokalen MacTex Installation ist das Paket installiert, der Fehler bleibt dennoch. Meine weitere Frage wäre eher generell ob ich da überhaupt den richtigen Weg gehe...

Viele Grüße,
Patrick

**Comment by ChristianLuxem** [comment]
Hallo @patm80 ,
hast du dir folgendes durchgelesen:
https://github.com/andygrunwald/FOM-LaTeX-Template#literaturverzeichnis

Reicht es vielleicht einfach, wenn du dort den Typ "article" zweckentfremdest und die Überschrift dann änderst? Sprich die für das Expose verwendete Literatur mit dem type "article" taggen und die Überschrift von Article in "Expose" ändern? Vielleicht hilft das ja schon. 

Zum kompilieren noch eine Frage: Nutzt du Docker oder die compile.sh? 
Wenn es bei dir lokal installiert ist, sollte beim kompilieren mit der compile.sh kein Fehler auftreten. Das Nachinstallieren in Docker musst du wenn dann natürlich auch erstmal an der richtigen Stelle (Dockerfile) angeben.

**Comment by patm80** [comment]
Hey Christian,

ich hatte den Abschnitt gelesen, bin da aber nicht auf die Idee gekommen. Danke für den Hinweis!
Ich müsste halt die Literaturverzeichnisse auf unterschiedlichen Seiten angeben ... Aber das sollte ja kein Problem sein, kann ja auf der jeweiligen Seite den jeweiligen \printbibliogrphy Command angeben. Mir stellt sich gerade noch eine Frage: Es wird bei mir Literatur geben, welche in beiden Literaturverzeichnissen vorkommen. Ich möchte halt diese Literatur nicht ausschließen. Das könnte ich ja aber vermutlich umgehen indem ich so einerseits für das eine Literaturverzeichnis als article tagge und dann noch einen Eintrag vom gleichen Werk habe als nicht article. Ich hoffe es ist einigermaßen verständlich was ich meine. 

Generell nutze ich den Docker Container. Hatte schon versucht den 'tlmgr install' Command zum Dockerfile hinzuzufügen. Das hatte aber leider nicht geklappt. Mit dem Script hat es aber funktioniert.

Gruß,
Patrick

**Comment by ChristianLuxem** [comment]
Hey Patrick,

ja das hast du richtig verstanden und sollte auch mit Quellen die in beide Verzeichnisse gehören kein Problem sein.
Wenn ich das richtig lese, ist das package multibbl allerdings sowieso schon in TexLive enthalten, welches in unserem Docker-Container installiert wird. Du müsstest also wahrscheinlich gar nichts ändern, sondern kannst es so schon einfach nutzen ohne etwas ändern zu müssen. Das kannst du also auch nochmal probieren.

**Comment by patm80** [comment]
Hey Christian,

vielen Dank für deinen schnelle Hilfe! Ich habe es jetzt anders gelöst und mich da an den folgenden Link gehalten:
[https://tex.stackexchange.com/questions/383484/package-biblatex-error-incompatible-package-multibib](url)

Das Packet konnte ich soweit leider nicht wegen des genannten Errors nicht einbinden. Ich habe dann mal was gesucht und vermute, dass das Packet nicht mehr benötigt wird, weil diese Funktionalität mittlerweile Teil von Latex selbst ist und gar kein Paket mehr benötigt wird. Habe es jedenfalls jetzt hinbekommen. 

Vielen Dank für die schnelle Hilfe!

Viele Grüße,
Patrick
