### ISSUE TITLE
Times New Roman

### ISSUE THREAD

**Issue by patm80** [andygrunwald/FOM-LaTeX-Template#116]
Hallo zusammen,

ich bekomme Times New Roman nicht wirklich zum laufen. Habe das Template soweit nicht verändert, auch nicht die gesetzten Einstellungen. Bin gerade etwas verwirrt und wollte hier nur mal nachfragen ob ich da etwas falsch verstehe. Im FOM Leitfaden soll ja Times New Roman verwendet werden.
Meine Schriftart sieht im Dokument wie folgt aus:
![grafik](https://user-images.githubusercontent.com/17497102/61578871-9123c880-aafd-11e9-94bf-43188bee7941.png)

Sorry, wenn das ne dumme Frage ist aber bin gerade unsicher, da es nicht die Times New Roman ist wie ich sie kenne und ich sicher gehen möchte, dass ich nicht noch was vergessen habe oder ähnliches.

Gruß,
Patrick

**Comment by ChristianLuxem** [comment]
Hallo,

wir benutzen Helvetica, wie hier erklärt:
https://latex-kurs.de/fragen/schriftarten/Times_New_Roman.html

Du kannst das natürlich für dich selbst ändern wie du willst. 
Bisher hatte soweit ich weiß noch niemand Probleme damit in der FOM. Ich weiß auch, dass Arial beispielsweise erlaubt sein soll.

**Comment by patm80** [comment]
Hey.

alles klar, also funktioniert alles wie zu erwarten. Danke dir für die Antwort!
Ich schließe das Ticket dann jetzt damit.

Gruß,
Patrick
