### ISSUE TITLE
Kompilieren nicht mehr ohne Python möglich

### ISSUE THREAD

**Issue by SimonHaak** [andygrunwald/FOM-LaTeX-Template#118]
Durch den Merge von PR #98 ist es nicht mehr möglich einfach nur TexLive 2019 zu installieren und zu kompilieren!
Stattdessen haben wir uns mit dem Merge noch Abhängigkeiten zu Python und dem Python Package Pygments eingebaut. Das finde ich persönlich eher schade. Schließlich benötigenja vermutlich nicht unbedingt alle, die dieses Template einbauen auch code highlighting in ihrem Dokument.

Meiner Meinung nach haben wir zwei Optionen:
1) Die Abhängigkeit in der Readme näher beschreiben und entsprechend auch die Installationsanleitung anpassen
2) Minted wieder ausbauen und meinetwegen in die Readme aufnehmen wie man schöneres Syntax Highlighting hinbekommen könnte.

Das Repo in einem Zustand zu lassen, in dem das Dokument ohne Docker nicht kompilierbar ist, und auch keine entsprechende Anleitung dabei zu legen fänd ich sehr schade.

Was sagt ihr? Welche Option ist besser?

**Comment by andygrunwald** [comment]
> Das Repo in einem Zustand zu lassen, in dem das Dokument ohne Docker nicht kompilierbar ist, und auch keine entsprechende Anleitung dabei zu legen fänd ich sehr schade.

Da stimme ich dir komplett zu.
Welche Option nun besser ist, ist in der Tat, eine gute Frage.
Aus dem Stehgref klingt Option 2) für mich nach einem gangbaren Weg.

@zebastian @ChristianLuxem Was denkt ihr darüber?

**Comment by ChristianLuxem** [comment]
Sehe ich genauso. 
Wir sollten Minted auskommentieren (ohne Docker) und in der Readme.md dann beschreiben wie man:

1. Das Highlighting wieder einbaut
2. Die erforderlichen Abhängigkeiten (Python) am einfachsten installiert (Mac & Windows)

In dem Docker-File schadet die Abhängigkeit erstmal nichts, da kann man dann auch darauf hinweisen, dass Docker die empfohlene Umgebung ist, die bereits alle Abhängigkeiten mitbringt.
Ich bin weiterhin überzeugt davon, dass wir mit Docker weniger Probleme uns ins Haus holen, weil dort bereits alles fertig konfiguriert ist. 
Trotzdem kann ich natürlich die Anforderung an eine Installation ohne Docker verstehen. 

Jetzt die Frage der Fragen: Wer hat Zeit diese Änderungen vorzunehmen? Kannst du das übernehmen @SimonHaak ?

**Comment by zebastian** [comment]
Hi Leute,
ich kann mir das bei Gelegenheit anschauen. Ist ja schließlich mein Patch.
Kann aber ein paar Tage dauern...
VG
