### ISSUE TITLE
Inhaltsverzeichnis: Abstand zum unteren Seitenrand zu gering

### ISSUE THREAD

**Issue by flotila** [andygrunwald/FOM-LaTeX-Template#120]
Hallo zusammen,

ich habe ein Problem mit dem Inhaltsverzeichnis:
Der Abstand auf der ersten Seite meines Inhaltsverzeichnisses zum unteren Seitenrand ist fast nicht vorhanden. Aufgrund der Anzahl der Gliederungspunkte ist aber ein Seitenwechsel erfolgt. Wie Kann ich auch auf der ersten Seite einen sauberen Abstand zum unteren Seitenrand bekomme?

[Inhaltsverzeichnis.pdf](https://github.com/andygrunwald/FOM-LaTeX-Template/files/3493636/Inhaltsverzeichnis.pdf)

Danke & viele Grüße,
Florian

**Comment by ChristianLuxem** [comment]
Hi @flotila ,
schau mal hier:
https://tex.stackexchange.com/questions/19762/change-margins-on-the-first-of-tableofcontents-page-only

**Comment by flotila** [comment]
Hi @ChristianLuxem ,
danke Dir, das sieht gut aus. Ich habe folgende zwei Zeilen in der thesis_main.tex direkt oberhalb des Befehls `\tableofcontents` eingefügt:
`\addtocontents{toc}{\protect\enlargethispage{-20mm}}`
`\clearpage`

20mm, da der Abstand zum unteren Seitenrand laut Leitfaden 2018 2cm beträgt. 

Ich muss bei Gelegenheit noch das Verzeichnis ausdrucken und mit dem Lineal nachmesse, ob es auch wirklich passt.

Viele Grüße,
Florian

**Comment by ChristianLuxem** [comment]
@flotila ,
falls die Lösung funktionieren sollte, kannst du gerne einen Merge-Request stellen um die Lösung auch anderen zur Verfügung zu stellen. 
Ich schließe das Ticket dann erstmal.
