### ISSUE TITLE
Anhang einfügen

### ISSUE THREAD

**Issue by flotila** [andygrunwald/FOM-LaTeX-Template#121]
Hallo zusammen,
ich bin gerade etwas doof:
Wie kann ich meinen Anhang einfügen? In Form von Anhang A1, A2, Anhang B1 etc.
Das müsste doch per `\appendix` funktionieren oder? Irgendwie kriege ich das gerade nicht hin.
Laut Leitfaden soll der Anhang vor dem Literaturverzeichnis eingefügt werden... Hat jemand einen Tipp?
Danke & viele Grüße,
Florian

**Comment by ChristianLuxem** [comment]
Hallo @flotila ,
hast du eine Lösung gefunden? 
Teile die Lösung gerne mit uns, vielleicht haben andere Leute in Zukunft dasselbe Problem..

**Comment by kirey19** [comment]
Ich habe eine Lösung schätze ich.
Ich habe in der main folgendes eingefügt (fett):
\input{kapitel/kapitel/kapitel_7.tex}
**\input{kapitel/anhang/leitfaden,tex}**

Und habe in der Datei leitfaden.tex so gestartet:
\newpage
\section*{Anhang 1: Leitfaden}
\addcontentsline{toc}{section}{Anhang}

Der Titel der Anhänge soll ja im Inhaltsverzeichnis nicht auftauchen, sondern nur stellvertretend "Anhang". Falls du weitere Dateien im Anhang haben möchtest, lässt du dann einfach das addcontentsline weg bei den nächsten.

**Comment by ChristianLuxem** [comment]
Scheint gelöst zu sein, daher schließe ich das Ticket.
