### ISSUE TITLE
Fehlerhinweis beim Kompilieren

### ISSUE THREAD

**Issue by kirey19** [andygrunwald/FOM-LaTeX-Template#122]
Hallo zusammen, 

kann sich jemand einen Reim auf diesen Fehler beim Kompilieren machen?

**! Package minted Error: You must invoke LaTeX with the -shell-escape flag.

See the minted package documentation for explanation.
Type  H <return>  for immediate help.
 ...

l.23 \usepackage
                [scaled=0.9]{helvet} % Behebt, zusammen mit Package courier,...**

Habe bisher nur meine Meta-Daten aktualisiert. Den Fehler kann man mit ganz viel Enter-Drücken wegklicken, sodass die pdf "augenscheinlich" fehlerfrei gebaut wird. Aber ich bin mir halt nicht ganz sicher. Hatte schon gelesen, dass das zB ein Fehler ist, der auftaucht, wenn man über TexStudio kompiliert - ich mache das aber über die shell durch Aufruf der compile.bat

Danke!

**Comment by SimonHaak** [comment]
Hallo @kirey19 ,
Du kommst hier auf das gleiche Problem wie in #118 beschrieben.
Am besten entfernst du die Zeile aus der thesis_main.tex Datei in der das Paket minted eingebunden wird. (wahrscheinlich irgendwas mit \usepackage{minted} o.ä. Kann da gerade leider nicht genauer schauen.
Außerdem wird im Text, also in einer der Kapitel.tex Dateien erklärt wie das minted paket verwendet wird. Den Teil musst du auch ausbauen, danach sollte der Fehler weg sein.

Außer natürlich du möchtest das Code highlighting verwendet, dass das mited Paket macht. Dann müsstest du dir perl installieren.
Beste Grüße,
Simon Haak

**Comment by kirey19** [comment]
perfekt! danke!
