### ISSUE TITLE
Bibliography: Urldate bei @online Eintrag

### ISSUE THREAD

**Issue by florianbosten** [andygrunwald/FOM-LaTeX-Template#13]
Hallo zusammen,

vielleicht könnt ihr mir ja helfen. Ich möchte nicht ausschließen, dass es etwas total simples ist.

Ich habe mir für meine Internetquellen einen eigenen BibliographyDriver geschrieben:

\DeclareBibliographyDriver{online}{%
  \printnames{author}%
  \newunit\addcolon\space
  \printfield{title}%
  \setunit*{\addcomma\space}%
  \printlist{publisher}%
  \newunit\newblockpunct
  \printlist{location}%
  \setunit*{\space}%
  \printfield{year}%
  \setunit*{\addcomma\space}%
  \printfield{url}%
  \setunit*{\space}%
  \printfield{urldate}%
  \finentry}

Mein Eintrag im Literaturverzeichnis sieht so aus:
@online{Bechtold.2001,
 author = {Bechtold, Richard and Dangle, Kathleen Coleman},
 year = {2001},
 title = {Lessons Learned Implementing the CMM for Small Organizations: Their Application to the CMMI},
 url = {https://seir.sei.cmu.edu/seir/domains/CMMi/Implement/SEPG2001at-msic/SEPG2001at-msic.pdf},
 urldate = {2013-12-30},
 address = {Pittsburgh and Pennsylvania},
 edition = {1},
 publisher = {{Software Engineering Institute,~Carnegie Mellon University}}
}

Bei der Angabe von Urldate im Typ Proceedings (nicht selbst definiert) wird das Datum wunderhübsch angedruckt. Mein Workaround für "online" war nun das Datum einfach in das Feld "note" zu packen. Aber cool ist das auch nicht. Ich will wissen wieso das nicht funktioniert ;)

Ich arbeite natürlich mit dem Template, Biber ist aktuell. 

Viele Dank!

**Comment by nameless66** [comment]
Das Problem / Lösung wird auf folgender Seite beschrieben:
http://tex.stackexchange.com/questions/56904/biblatex-verbose-urldate-is-getting-ignored

**Comment by andygrunwald** [comment]
Benötigt dieses Ticket Änderungen am Code?
Oder Verweisen wir auf den Link?

**Comment by nameless66** [comment]
Nein, da im ursprünglichen Code des Templates urldate nicht verwendet wird. Falls dieses Feld nun doch benutzt werden möchte, kann dies schlicht mit \printurldate erfolgen (anstatt \printfield{urldate}%)

Bsp.:
%% Definiert @Online Eintrag nach dem Schema
%% von Theisen: Wissenschaftliches Arbeiten (Oxford-Style)
\DeclareBibliographyDriver{online}{%
  \printnames{author}%
  \setunit*{\space (}%
  \printfield{year}\newunit{)}%
  \newunit\addcolon\space
  \printfield{title}%
  \setunit*{,\space}%
  \printfield{edition}%
  \newunit\newblockpunct
  \urlstyle{same}
  \printfield{url}%
  \setunit*{\space}%
  \printurldate
  \finentry}

**Comment by andygrunwald** [comment]
So wie ich das sehe ist dieses Issue behoben, richtig @florianbosten & @nameless66 ?
Wenn nicht, bitte melden, dann mach ich das Ticket wieder auf.
