### ISSUE TITLE
Runde Klammern um die Jahreszahl in der Fußnote

### ISSUE THREAD

**Issue by 0xLenny** [andygrunwald/FOM-LaTeX-Template#131]
Hallo Andy,

du gibst in deiner Doku an, dass mit dem Befehl "\footcite[Vgl. ][Seite 1]{Balzert.2008}" der Output "Vgl. Balzert et al. (2008), Seite 1." generiert wird. In der Beispiel PDF wird die Fußnote auch ohne ( ) angezeigt.

Lieder fehlt die runde Klammer um die Jahreszahl. Gibt es hierfür eine Lösung? Ich konnte im Internet leider keine für mich verständliche Lösung finden.

Nachtrag: Auch bei der Ausführung im Docker Container erhalte ich das selbe Ergebnis. Anscheinend gibt es auch Probleme mit dem Abkürzungsverzeichnis, die Überschrift fehlt.

Gruß 
Lenny.

**Comment by SimonHaak** [comment]
Moin,
bin zwar nicht Andy, aber...
Das die Klammern nicht angezeigt werden ist kein Bug. Der Text ist nach der Anpassung auf den neuen Leitfaden nicht aktualisiert worden. Das muss natürlich noch gemacht werden.
Laut dem aktuellen Leitfaden für wissenschaftliche Arbeiten an der FOM werden in Fußnoten keine Klammern verwendet. Eine Fußnote soll wie folgt aussehen:
Vgl. Balzert, H. et al., Wissenschaftliches Arbeiten, 2008, S. 1.

Wenn du (aus welchem Grund auch immer) lieber die alte Version nutzen möchtest müsstest du in der Datei thesis_main.tex die Zeilen 76-94 mit einem % am Anfang der Zeile auskommentieren und in den Zeilen 97-108 das %-Kommentarzeichen entfernen.

Die allermeisten Dozenten erwarten inzwischen allerdings das Format nach dem neuen Leitfaden.

**Comment by ChristianLuxem** [comment]
Hallo @0xLenny ,
kannst du die Doku an der entsprechenden Stelle anpassen und einen Pull-Request stellen? Das würde uns sehr helfen, danke.

**Comment by 0xLenny** [comment]
Hallo Simon,

du meinst wohl eher 112-130 (%%%% Neuer Leitfaden (2018)) auskommentieren und  132-144 (%%%%% Alter Leitfaden. Ggf. Einkommentieren und Bereich hierüber auskommentieren) einkommentieren.

Leider erhalte ich hier auch das selbe Ergebnis, die Jahreszahlen werden nicht in Klammern angezeigt.
Ich werde mit dem Prof. sprechen und fragen, wieso er denn die Abweichung vom Leitfaden möchte.
Denn ich hab jetzt schon einige Stunden damit verbracht das Problem zu lösen anstatt die Thesis zu schreiben:D

Gruß

**Comment by SimonHaak** [comment]
Hallo,
völlig richtig.
Je nachdem wie die Anforderung deines Dozenten aussieht könntest du auch \fullfootcite[Vgl. ][Seite. 1]{Balzert.2008} benutzen. Damit hättest du die Klammern drin.

Vgl. Balzert, Helmut et al. (2008), Seite 1.

Allerdings ist dadurch der Vorname drin. 

Dein Ansatz mit dem Betreuer zu sprechen sollte aber tatsächlich der beste sein. Laut Leitfaden ist es sogar egal, wenn das Format von Fußnote & Literaturverzeichnis abweicht, wenn es daran liegt, dass ein Literaturverwaltungsprogramm genutzt wird.

**Comment by ChristianLuxem** [comment]
Hallo,
das Problem scheint ja erledigt zu sein, daher schließe ich das Ticket vorerst.
