### ISSUE TITLE
Schriftart Arial statt Times New Roman

### ISSUE THREAD

**Issue by DapDallas** [andygrunwald/FOM-LaTeX-Template#133]
Hey, ich bin gerade dabei die Latex Vorlage zu nutzen. Mir ist dabei aufgefallen, dass das kein Times New Roman ist, sondern Arial.
Ich habe in der thesis_main.tex gesehen, dass der Author sich nach den Angaben der verlinkten Webseite (um Times NR zu erstellen) gerichtet hat, jedoch ist das keines.

Hat jemand eine Lösung? Ich hab schon verschiedenes Probiert und auch was gegoogelt, werde jedoch nicht schlauer, wie man die Textart ändert.

Gruß
Daniel

**Comment by ChristianLuxem** [comment]
Hallo @DapDallas ,
in dem noch offenen Pull-Request ist bereits eine Arial-Lösung eingebaut, diese kannst du gerne schon für deine Zwecke nutzen:
```
% Schriftart Arial
\usepackage{fontspec}
\setsansfont{Arial}
\renewcommand\familydefault{\sfdefault}
```

Einfach diese Zeilen in der thesis_main.tex einfügen, am besten nach der Nutzung der anderen Packages. Kannst du dir auch hier ansehen:
https://github.com/andygrunwald/FOM-LaTeX-Template/pull/110/files#diff-6852696efeb5e7ac9510f041876c2073
Falls die Änderungen bei dir gut funktionieren und du diese für sinnvoll hältst, kannst du auch gerne danach einen Pull-Request stellen.

**Comment by DapDallas** [comment]
ok, ich weiß nicht ob ich das nun richtig gemacht habe, aber ich habe da nun Times New Roman hinzugefügt.

`\usepackage{fontspec}
% Schriftart Times New Roman
\setsansfont{Times New Roman}

% Schriftart Arial
%\setsansfont{Arial}
\renewcommand\familydefault{\sfdefault}`

Mein Problem war halt, dass das Dokument kein Times New Roman ist.
Ich habe das Projekt auf overleaf bearbeitet und dort festgestellt, dass man den Compiler auf LuaLatex stellen muss. Ist mir entweder entgangen oder wurde nicht erwähnt, das das verwendet wird.

Naja, mit dem Code funktioniert wenigstens nun Times New Roman

**Comment by ChristianLuxem** [comment]
Im neuesten PR ist ja auch der Compiler auf LuaLatex geändert worden. Wir prüfen noch, ob das Vorteile bei der Erstellung hat. 
Ich schließe erstmal das Ticket.
