### ISSUE TITLE
Literaturverzeichnis: unnötiges Leerzeichen

### ISSUE THREAD

**Issue by ZmaD1** [andygrunwald/FOM-LaTeX-Template#138]
Hallo Andy,

erstmal vielen Dank für das tolle Template! 

Wenn im Literaturverzeichnis die Variable "urldate" mit ausgegeben wird, aber die Variable "urltime" fehlt, wird ein unnötiges Leerzeichen erstellt. 

Beispiel:
> Brink,Sascha(AngularJS,  2018):  AngularJS  -  Was  ist  Angular?,URL:  <https : / /angularjs.de/buch/was-ist-angularjs> (2018-12-20) [Zugriff: 2019-01-02 23:30 Uh**r]**

> Hochschule` für Oekonomie & Management(Onlinecampus, 2018): Onlinecampus,URL:<https://www.campus.bildungscentrum.de> (2018) [Zugriff: 2018-11-0**1 ]**

Gruß 
Flo

**Comment by SimonHaak** [comment]
Moin,
bin zwar nicht Andy, aber die Anpassungen an den aktuellen Leitfaden hatte ich damals eingeführt. Der "Fehler" ist in der Datei modsBiblatex2018.tex. Den Pullrequest zur Fehlerbehebung habe ich gerade schon gestellt.
Es reicht den Zeilenumbruch am Ende von Zeile 90, sowie die führenden Leerzeichen aus Zeile 91 zu entfernen. Dann sieht das ganze so aus:
![grafik](https://user-images.githubusercontent.com/39888707/71936568-2bf68900-31aa-11ea-8031-d2483ec70eee.png)

**Comment by ChristianLuxem** [comment]
Hallo zusammen,
ich habe den Bugfix in den Master gemerged. Danke für eure Arbeit und das Melden des Fehlers! Ich schließe das Ticket erstmal, sollte der Fehler noch nicht vollständig behoben sein, dann kommentiert einfach kurz und ich öffne wieder.
