### ISSUE TITLE
Nicht einzigartige Fußnoten bei selbem Autor

### ISSUE THREAD

**Issue by thesiswriter1** [andygrunwald/FOM-LaTeX-Template#140]
Hallo zusammen,

ich habe ein kleines Problem von welchem ich aktuell nicht verstehe wie ich es los werde. Ich habe zwei verschiedene Quellen vom selben Autor aus dem selben Jahr. Wenn ich die Fußnoten nun verwende, werden sie automatisch nach der Jahreszahl mit einem Buchstaben versehen, welcher fortlaufend für weitere Fußnotenangaben dieser Quelle ist (a, b, c...). Ich habe recherchiert und herausgefunden, dass es daran liegen könnte, dass Biblatex die Fußnoten "unique" machen möchte, aber diese Funktionalität ist per default auf false gesetzt (laut Dokumentation). Ich kann nirgends finden, dass ihr diese wieder aktiviert hättet (bin jetzt aber auch kein LaTeX Profi).

Habt ihr einen Rat für mich, wie ich diese Funktionalität los werden könnte?
 
Danke für eure Arbeit, sie war mir bereits eine riesige Hilfe!

Viele Grüße

**Comment by xremix** [comment]
Ich wäre da auch an einer Lösung interessiert - habe das gleiche Problem.

Viele Grüße

**Comment by moewew** [comment]
Im Kontext des FOM-Stil - wie ich ihn aus zweiter Hand verstehe - wäre eventuell
```latex
\DeclareExtradate{%
  \scope{
    \field{labelyear}
    \field{year}
  }
  \scope{
    \field{usera}
  }
}
```
angebracht. Dann würde der Buchstabe nur angefügt, wenn Autor, Schlagwort/Kurztitel in `usera` und das Jahr übereinstimmen.

Siehe auch https://tex.stackexchange.com/q/523786/35864.

Bei anderen Stilen ist es entweder keine gute Idee, den Buchstaben zu entfernen, da sonst die Eindeutigkeit verloren geht, oder es gibt andere Methoden, das zu erreichen. Das ist aber von Stil zu Stil verschieden, daher möchte ich ohne Minimalbeispiel dazu keine weitere Aussage machen.

**Comment by SimonHaak** [comment]
@moewew der Ansatz ist völlig richtig.
In unserem Stil bauen wir das Feld Extradate explizit wieder ein. Denke deshalb wird das entsprechend auch angezeigt. Das Feld usera wird logischerweise normalerweise nicht berücksichtigt. Wir missbrauchen das Feld an der Stelle ja ein wenig.

Getestet habe ich wie folgt:

Dreimal den gleichen Eintrag eingefügt. Zweimal exakt gleich und nur den Bibkey geändert, einmal auch das Keyword angepasst.
![grafik](https://user-images.githubusercontent.com/39888707/72272457-ef52e380-3628-11ea-9b07-398c71180324.png)

Ergebnis ist wie folgt und damit richtig:
![grafik](https://user-images.githubusercontent.com/39888707/72272541-16a9b080-3629-11ea-83a7-a891a88430ce.png)

![grafik](https://user-images.githubusercontent.com/39888707/72272424-e235f480-3628-11ea-8729-969d076a2442.png)

**Comment by moewew** [comment]
Es gibt durchaus noch ein paar andere Baustellen im `biblatex`-Stil, die man sich ansehen könnte.

* Die Nutzung von `\langde` und `\langen` ist im `biblatex`-Kontext ungewöhnlich. `biblatex` hat stattdessen sogenannte bibstrings, die zur Lokalisierung verwendet werden können und sollten. 
So würde das `\langde{keine Datumsangabe}\langen{no Date}` in

  https://github.com/andygrunwald/FOM-LaTeX-Template/blob/e09129944cffbd4a761b892ab54056e6d4bdd07b/skripte/modsBiblatex2018.tex#L98

  besser zu

  ```latex
  \bibstring{nodate}
  ```

* An einigen Stellen fehlen `%`s an den Zeilenenden oder anderen Stellen um ungewollte Leerzeichen zu verhindern (https://tex.stackexchange.com/q/7453/35864).

* Das Löschen der Felder mit `\clearfield` in `\AtEveryBibitem` ist auch gerade wegen der ganzen `\ifentrytype`s sehr umständlich.

  https://github.com/andygrunwald/FOM-LaTeX-Template/blob/e09129944cffbd4a761b892ab54056e6d4bdd07b/skripte/modsBiblatex2018.tex#L8-L45

  (Auch hier fehlen Teilweise `%`s am Zeilenende.) Für `url`, `doi`, `eprint`, `isbn`/`issn`/... hat `biblatex` spezielle Optionen, um die Ausgabe zu unterdrücken (`url=false,`, `doi=false,`, `eprint=false,`, `isbn=false,`; praktischerweise wird bei `@online`-Einträgen die `url` selbst mit `url=false,` nicht unterdrückt). Andere Felder werden schöner mit `\DeclareSourcemap` unterdrückt. Siehe auch https://tex.stackexchange.com/q/491887/35864, https://tex.stackexchange.com/q/440251/35864, https://tex.stackexchange.com/q/229428/35864 bei TeX.SX.

* Statt

  https://github.com/andygrunwald/FOM-LaTeX-Template/blob/e09129944cffbd4a761b892ab54056e6d4bdd07b/skripte/modsBiblatex2018.tex#L53-L56

  kann man mit einer neuen Version auch einfach nur
  ```latex
  \renewcommand*{\mkbibcompletename}{\mkbibemph}
  ```
  schreiben.

* https://github.com/andygrunwald/FOM-LaTeX-Template/blob/e09129944cffbd4a761b892ab54056e6d4bdd07b/skripte/modsBiblatex2018.tex#L87-L91

  Eigentlich können `biblatex`s Datumsfelder (wie `urldate`) von sich aus direkt mit Uhrzeiten umgehen. Es bedarf keines zusätzlichen `...time`-Feldes. Dazu muss die Zeit im `...date`-Feld im ISO8601-Format eingegeben werden, also

  ```latex
  urldate = {2020-01-13T20:46:00},
  ```

  und die Ausgabe der Zeit muss mit `...dateusetime=true,` angefragt werden.

* Das Makro `cite` wird gleich zwei mal umdefiniert.
 
  https://github.com/andygrunwald/FOM-LaTeX-Template/blob/e09129944cffbd4a761b892ab54056e6d4bdd07b/skripte/modsBiblatex2018.tex#L157-L167

  und

  https://github.com/andygrunwald/FOM-LaTeX-Template/blob/e09129944cffbd4a761b892ab54056e6d4bdd07b/skripte/modsBiblatex2018.tex#L214-L225

  Natürlich gewinnt die zweite Redefinition, sodass die erste überflüssig ist.

* Da die ursprüngliche Änderung in

  https://github.com/andygrunwald/FOM-LaTeX-Template/blob/e09129944cffbd4a761b892ab54056e6d4bdd07b/skripte/modsBiblatex2018.tex#L199-L203

  nun wieder entfernt wurde, tut das Makro eigentlich nichts anderes als die Standarddefinition. Die Redefinition könnte also weg.

* Auch

  https://github.com/andygrunwald/FOM-LaTeX-Template/blob/e09129944cffbd4a761b892ab54056e6d4bdd07b/skripte/modsBiblatex2018.tex#L172-L193

  ist problematisch.

  So kann z.B. das
  ```latex
  \iffieldundef{volume}
    {}
    {\printfield{volume}}
  ```
  durch
  ```latex
  \printfield{volume}%
  ```
  ersetzt werden.

  Leerzeichen und andere Zeichensetzung sollten niemals dadurch erzeugt werden, dass sie direkt in einem bibmacro stehen. Zeichensetzung zwischen Feldern sollte mit `\setunit` und Freunden erledigt werden, Zeichensetzung in einem Feld mit `\DeclareFieldFormat`. Text wie "Nr." sollte ebenfalls nur in einem `\DeclareFieldFormat` auftauchen.

**Comment by SimonHaak** [comment]
Vermutlich hat niemand etwas dagegen, wenn du deine vorgeschlagenen Änderungen testest und einbaust. Ein Großteil des Zitierstils ist auf Basis meines latex Halbwissens entstanden, da ist sicher was den Stil angeht noch Luft nach oben. Gleiches gilt für die englische Version. 

Also: Feel Free. Würde das ganze sicherlich wartbarer machen, falls Änderungen am Stil durchgeführt werden müssen.

**Comment by moewew** [comment]
Da ich die Vorgaben nicht kenne, möchte ich das selbst ungern machen. Ich bin gerne bereit, bei konkreten Fragen zu helfen (so bin ich ja hier überhaupt hergekommen) oder (mehr oder weniger hilfreiche oder konkrete) Hinweise wie den oben zu teilen. Aber für die Implementation sowie die meiner Meinung nach dann auch zugehörige weitere Betreuung des Codes darüber hinaus (falls Fehler gemeldet werden oder die Vorgaben sich wieder ändern) fehlt mir leider sowohl die Zeit als auch die Motivation.

**Comment by ChristianLuxem** [comment]
Hallo @moewew ,
Die Vorgaben die zu beachten sind, sind hier beschrieben:
https://github.com/andygrunwald/FOM-LaTeX-Template#ich-m%C3%B6chte-mithelfen-diese-vorlage-zu-verbessern

Ein OpenSource Projekt lebt davon, dass Leute freiwillig Quellcode und Verbesserungsvorschläge einbringen, niemand wird dazu verpflichtet, dass der Quellcode richtig ist oder in Zukunft von der selben Person gewartet werden muss. Du kannst also durchaus die Vorschläge gerne als Pull-Request bereitstellen, ohne dich für die Zukunft zu irgendwas zu verpflichten. 
Ich kann es natürlich verstehen, falls dir dafür die Zeit und Motivation fehlt, fände das aber trotzdem schade. 
Trotzdem danke für deinen Input. 
@SimonHaak  ich hatte deinen einen Pull-Request ja noch nicht gemerged, da ich gerne noch das praktische Beispiel in der PDF hätte, damit wir bei Änderungen direkt testen können, ob alles noch funktioniert. Eventuell willst du ja dann direkt diese Änderungen auch implementieren?

**Comment by ChristianLuxem** [comment]
Fix ist gemerged, ich würde daher das Ticket nun schließen. 
Danke sehr
