### ISSUE TITLE
Literaturverzeichnis und Zitieren nach APA Richtlinien...

### ISSUE THREAD

**Issue by haenno** [andygrunwald/FOM-LaTeX-Template#148]
Hallo und vielen Dank für die tolle Arbeit! Ich sitze gerade an meiner ersten Seminararbeit.

Gibt es eine Möglichkeit auf das Zitieren nach APA Richtlinien umzustellen?

Wenn ich es richtig verstehe, müsste der ganze Fußnotenblock auf jeder Seite raus und dafür hinter jeder Stelle ein Verweis im Text "(Autor, Jahr)" hinterlegt werden. 

Auch müsste wohl im Literaturverzeichnis die Internetquellen mit eingefügt werden.

Vielleicht gibt es ja eine einfache Lösung...

**Comment by haenno** [comment]
> Auch müsste wohl im Literaturverzeichnis die Internetquellen mit eingefügt werden.

Hab ich geschafft mit Änderungen in der **thesis_main.tex**:
Auskommentieren der Zeilen
```
408 \printbibliography[nottype=online,heading=bibintoc,title={\langde{Literaturverzeichnis}\langen{Bibliography}}]
411 \newpage
418 \printbibliography[type=online,title={\langde{Internetquellen}\langen{Internet sources}}]
```
mit jeweils "%" voranstellen und...

...darunter nach Zeile 418 neu:

`\printbibliography[heading=bibintoc,title={\langde{Literaturverzeichnis}\langen{Bibliography}}]`

**Comment by andygrunwald** [comment]
Hey @haenno,

wie du gemerkt hast, unterstützt die Vorlage es nicht von Haus aus.
Es scheint aber, als hättest du eine Lösung gefunden.

Wärst du vielleicht bereit um das Vorgehen in der README zu dokumentieren und einen Pull Request zu senden? (siehe auch [Creating a pull request](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request)

**Comment by ChristianLuxem** [comment]
Die Aufteilung des Literaturverzeichnisses steht bereits in der Readme.md:
https://github.com/andygrunwald/FOM-LaTeX-Template#literaturverzeichnis
Falls dies nicht korrekt oder zu wenig sein sollte, kannst du wie von Andy beschrieben dort etwas hinzufügen.

Das Zitieren nach APA werden wir nicht einführen, da die jetzige Methode dem Leitfaden entspricht und daher auch für 99% der Benutzer richtig ist. Du kannst natürlich die Vorlage für dich selbst anpassen und Forken - Kein problem. Das Anpassen der Zitierweise wird allerdings etwas aufwändiger und erfordert einige LateX/Bibtex Kenntnisse. Am besten fragst du deinen Dozenten, ob die jetzige Zitierweise in Ordnung ist. Wie gesagt für bisher fast alle FOM-Studierenden war diese Zitierweise in Ordnung, da Sie dem Leitfaden von 2018 entspricht, woran sich die Dozenten orientieren.

**Comment by xremix** [comment]
Hallo zusammen, ich bin voll bei euch. Nur als kurze Anmerkung: Für einige Studienfächer (u.a. Wirtschaftspsychologie) gibt es eigene Leitfäden, welche nicht dem Standardleitfaden entsprechen und bei dem genannten Beispiel weiß ich, dass nach APA zitiert werden muss.

**Comment by haenno** [comment]
> steht bereits in der Readme.md

...auch die Kommentierungen der tex Dateien haben sehr geholfen -- Ich denke das ist wirklich ausreichend. Danke! :) 

> Das Anpassen der Zitierweise wird allerdings etwas aufwändiger und erfordert einige LateX/Bibtex Kenntnisse.

...genau das habe ich gestern Abend und Nacht auch festgestellt ;-)  Für mich als absoluten Latex-Neuling war das eine steile Lernkurve :)

Der Vollständigkeit halber: Die Fußnoten gehen natürlich ganz einfach raus indem man von 
`\footcite[Vgl.][S. 1]{Lucke2018}`
auf 
`\cite{...}`
umstellt.

Viel spannender ist da das anwenden der APA Richtlinien. Wie geschrieben, trifft uns der Leitfaden aus der Wirtschaftspsychologie hier auch in der Wirtschaftsinformatik. 
Die Argumentation des Profs kann ich hier gut nachvollziehen (Lesbarkeit und scheinbar auch akt. Verbreitung/Nutzung).

Ich will gerne das Template hier nutzen und werde daher versuchen die APA Richtlinien möglichst elegant einzubauen (was mir als Latex-Neuling schwer fallen wird). In der thesis_main.tex habe ich dazu um Zeile 117 alles zu Biblatex auskommentiert und mich auf die neue Datei 
`\input{skripte/modsBiblatexAPA}`
bezogen.

Darin ziehe ich mir im wesentlichen Code-Schnipsel aus diesen beiden Beiträgen:

[https://tex.stackexchange.com/questions/452228/modifying-bibliography-with-biblatex-biber-apa-style-locationpublisherdoi](https://tex.stackexchange.com/questions/452228/modifying-bibliography-with-biblatex-biber-apa-style-locationpublisherdoi)

[https://texwelt.de/fragen/2686/wie-formatiere-ich-ein-bibtex-literaturverzeichnis-fur-eine-deutschsprachige-ausgabe-nach-den-regeln-der-apa](https://texwelt.de/fragen/2686/wie-formatiere-ich-ein-bibtex-literaturverzeichnis-fur-eine-deutschsprachige-ausgabe-nach-den-regeln-der-apa)

Im Moment hänge ich (neben allerhand Fehlermeldungen beim PDF erstellen) daran, Inhalte im Literaturverzeichnis richtig aufzubauen. In der Ausgabe bei Internetquellen z.B. habe ich etwas durcheinander:

> Hochschule für Oekonomie & Management. (2018). Onlinecampus. Verfügbar 01. 11. 2018
unter https://www.campus.bildungscentrum.de

Müsste so sein:

> Hochschule für Oekonomie & Management. (2018). Onlinecampus. Verfügbar unter https://www.campus.bildungscentrum.de [ 01. 11. 2018].

Bei Büchern fehlt z.B. auch der Ort:

> Beckert, A. & Beckert, S. & Escherich, B. (2012). Mobile Lösungen mit SAP (1. Auﬂ.).
Galileo Press.

Müsste...

> Beckert, A. & Beckert, S. & Escherich, B. (2012). Mobile Lösungen mit SAP (1. Auﬂ.).
Bonn: Galileo Press.

Es bleibt also spannend :) Danke für eure Antworten!

**Comment by SimonHaak** [comment]
Moin,
normalerweise gilt der Leitfaden der Wirtschaftspsychologie die Wirtschaftinformatiker nicht. Das ist dann eine Entscheidung deines einzelnen Dozenten.

zum Datum:
Es gibt zwei Datumsfelder. "date" und "urldate". Ersteres steht für das Erstellungsdatum der Webseite, letzteres für den Zeitpunkt deines Aufrufs. 

zum Ort:
Versuch mal statt "address" "location" zu verwenden.

Beste Grüße.

**Comment by haenno** [comment]
Hallo noch mal,

das ganze war wirklich umfangreicher als gedacht. Daher [geforkt](https://gitlab.com/haenno/fom-latex-apa6). 

Die wesentlichen Zeilen daraus hier (als Ersatz an der passenden Stelle dazu in der thesis_main.tex):
`
%%%% APA START / Biblatex
%% Zitierung und Literaturverzeichnis nach APA6 der LMU
%% ---> Prof. wünscht APA6 nach LMU PDF Besipielen https://gitlab.com/haenno/fom-latex-apa6/-/blob/master/backup/hinweise-zur-apa.pdf
% Teillösungen von hier... 
% https://tex.stackexchange.com/questions/452228/modifying-bibliography-with-biblatex-biber-apa-style-locationpublisherdoi 
% https://texwelt.de/fragen/2686/wie-formatiere-ich-ein-bibtex-literaturverzeichnis-fur-eine-deutschsprachige-ausgabe-nach-den-regeln-der-apa
% https://tex.stackexchange.com/questions/452032/setting-maxcitenames-for-biblatex-apa (credit dahin für Lösung um die anzahl und wiederholungsnennungen, auch an den entdecker DaMiu)
% https://tex.stackexchange.com/questions/526434/edit-biblatex-apa-style  Lösung Punkt hinter OnlineQuellen entf.  nach Tip, DaMiu 

%% Literaturverzeichnis entsprechend abrufen mit:
% -  Internetquellen: (immer als @misc nicht @online!) 	Name Herausgeber Seite (analog Autor), 	Erscheinungsjahr, URL, Abrufdatum-URL
% -  Buch:(@book)				 Autoren,			 Erscheinungsjahr, Titel, ggfls. Hinweis auf Auflage/Band, Verlagsort, Verlagsname
% -  Zeitschriftenartikel(@article)   Autoren,			 Erscheinungsjahr, Titel des Artikel, Titel der Zeitschrift, Ausgabe mit Band- ggfls. Heftnummer, Seitenzahl(en)
% -  Weiter auch  möglich:, Herausgeberwerk (@incollection) und  Buchkapitel- oder beitrag(@inbook)
% (ungetestet bisher : Dissertationen (@phdthesis))

\usepackage[
    style           = apa6, 
    uniquelist      = false,    
    maxcitenames    = 6,
    backend         = biber,
	urldate         = short,
	uniquename 		= true,
	language		= ngerman
	]{biblatex} 
		
	%% START Block für Funktion (1. Nennung von 2-6 Autoren: Alle Namen, danach nur noch 1. Name + et.al) 
	\usepackage{lmodern} 
	\makeatletter
	\newcommand{\apamaxcitenames}{6}
	\DeclareNameFormat{labelname}{%
	  \ifthenelse{\value{uniquelist}>1}
		{\numdef\cbx@min{\value{uniquelist}}}
		{\numdef\cbx@min{\value{minnames}}}%
	  \ifboolexpr{test {\ifnumcomp{\value{listcount}}{=}{1}}
				  or test {\ifnumcomp{\value{listtotal}}{=}{2}}}
		{\usebibmacro{labelname:doname}%
		  {\namepartfamily}%
		  {\namepartfamilyi}%
		  {\namepartgiven}%
		  {\namepartgiveni}%
		  {\namepartprefix}%
		  {\namepartprefixi}%
		  {\namepartsuffix}%
		  {\namepartsuffixi}}
		{\ifboolexpr{test {\ifnumcomp{\value{listtotal}}{>}{\apamaxcitenames}}
					 or test {\ifciteseen}}
		 {\ifnumcomp{\value{listcount}}{<}{\cbx@min + 1}
		   {\usebibmacro{labelname:doname}%
			 {\namepartfamily}%
			 {\namepartfamilyi}%
			 {\namepartgiven}%
			 {\namepartgiveni}%
			 {\namepartprefix}%
			 {\namepartprefixi}%
			 {\namepartsuffix}%
			 {\namepartsuffixi}}
		   {}%
		  \ifnumcomp{\value{listcount}}{=}{\cbx@min + 1}
			{\ifnumcomp{\value{listcount}}{<}{\value{listtotal}}
			  {\printdelim{andothersdelim}\bibstring{andothers}}
			  {\usebibmacro{labelname:doname}%
				{\namepartfamily}%
				{\namepartfamilyi}%
				{\namepartgiven}%
				{\namepartgiveni}%
				{\namepartprefix}%
				{\namepartprefixi}%
				{\namepartsuffix}%
				{\namepartsuffixi}}}
			{}%
		  \ifnumcomp{\value{listcount}}{>}{\cbx@min + 1}
		   {\relax}%
		   {}}%
		 {\usebibmacro{labelname:doname}%
		   {\namepartfamily}%
		   {\namepartfamilyi}%
		   {\namepartgiven}%
		   {\namepartgiveni}%
		   {\namepartprefix}%
		   {\namepartprefixi}%
		   {\namepartsuffix}%
		   {\namepartsuffixi}}}}
	\makeatother 
	\DeclareLanguageMapping{ngerman}{ngerman-apa}
	%% ENDE Block für Funktion (1. Nennung von 2-6 Autoren: Alle Namen, danach nur noch 1. Name + et.al)
	
	\DeclareDelimFormat*{finalnamedelim}{\addspace\bibstring{and}\space} % In Parencite von "&" auf "und" ändern
	\hypersetup{hidelinks}  %Grüne Links auf Literaturverz. unterdrücken.
	\setlength\bibitemsep{1.3ex} % Abstände im Literaturverzeichnis erhöhen
	\setlength\bibnamesep{1.0ex}
	\AtBeginBibliography{\singlespacing} % Zeilenabstand im Literaturverzeichnis ist Einzeilig - siehe Leitfaden S. 14
	\urlstyle{same} %Standard-Font für Link anstelle der "Schreibmaschinenschrift"
	\DeclareFieldFormat[misc]{urldate}{[#1\printfield{urldate}].} 	% Anpassung @online + @misc Bibl: Datum in eckigen Klammern ans Ende
	\DeclareFieldFormat[misc]{title}{\mkbibemph{#1}} %Anpassung @online + @misc Titel Kursiv	
	\DeclareFieldFormat[misc]{url}{Verfügbar unter\space \url{#1}} 	%Anpassung @online + @misc Text vor URL
	\renewbibmacro*{url+urldate}{\usebibmacro{url}\setunit{\addspace}\usebibmacro{urldate}}  % URL vor Abrufdatum setzen + getrennte Wörter "Verfügbar" und "Unter" entfernen
%%%% APA ENDE`

Und noch eine formale Korrektur für das Literaturverzeichnis (für Einsatz an der Stelle Aufruf LitVerz,):
`
\newpage % Literaturverzeichnis

% Im Literaturverzeichnis "und" wieder durch "&" ersetzen	
	\DeclareDelimFormat*{finalnamedelim}{\addspace\&\space}

% Punkt hinter und vor der Jahreszahl entfernen	- Wichtig für Quell-Arten wie misc und online -- Sonst ein überflüssiger Punkt im LitVerz.
	\renewbibmacro*{author}{%
	\printtext{%
	\ifnameundef{author}
	{\usebibmacro{labeltitle}}
	{\printnames[apaauthor][-\value{listtotal}]{author}%
	\setunit*{\addspace}%
	\printfield{nameaddon}%
	\ifnameundef{with}
	{}
	{\setunit{}\addspace\mkbibparens{\printtext{\bibstring{with}\addspace}%
	\printnames[apaauthor][-\value{listtotal}]{with}}
	\setunit*{\addspace}}}%
	% \newunit\newblock%
	\usebibmacro{labelyear+extradate}}}

\printbibliography[heading=bibintoc,title=Literaturverzeichnis]

\newpage % Ehrenwörtliche Erklärung
`

Müsste eigentlich in die 'thesis_main.tex' oder eine gesonderte '/skripte/modsBiblatexAPA6.tex'. 

Um diese speziellen Anforderungen unseres Profs einzubinden waren schon einige Spezialanpassungen nötig (man bezieht sich auf ein PDF der LMU was auf APA6 aufbaut -- Also eigentlich auch schon überholt).

IMO wirklich zu aufwändig/umfassend um das hier angemessen zurückzuspielen. Zumal das ja wirklich nur eine Abweichung vom FOM Standart ist. 

Danke noch mal für die Hilfe + Viele Grüße,
haenno
