### ISSUE TITLE
Lesezeichen des Literaturverzeichnisses im PDF hat falschen Namen

### ISSUE THREAD

**Issue by FelixKohlen** [andygrunwald/FOM-LaTeX-Template#149]
Mir ist heute aufgeafllen, dass das Lesezeichen des Literaturverzeichnisses nicht korrekt dargestellt wird. Das Problem ist in der PDF-Datei im Repository als auch bei einer frisch erzeugten Datei zu finden. So sieht es im Adobe Reader aus:
![grafik](https://user-images.githubusercontent.com/1908401/79686120-4676de80-823e-11ea-9692-4e78e5d74290.png)

Ich nehme an, dass es von diesen beiden Zeilen erzeugt wird, und die Funktionenen für die entsprechenden Sprachen nicht richtig aufgelöst werden:
https://github.com/andygrunwald/FOM-LaTeX-Template/blob/a56bb10a3a12eb4aa10979c764222639e98a66a9/thesis_main.tex#L256

**Comment by SimonHaak** [comment]
Moin,
es liegt wohl eher an dem Befehl hier:
`\printbibliography[nottype=online,heading=bibintoc,title={\langde{Literaturverzeichnis}\langen{Bibliography}}]`

Ersetzt man den Teil in den eckigen Klammern mit "Literaturverzeichnis" ergibt das das richtige Ergebnis. Schade nur, dass die englische Version dann nicht mehr richtig funktioniert.

**Comment by haenno** [comment]
Gleiches passiert übrigens bei Anhang (wenn verwendet):

`
\addcontentsline{toc}{section}{\langde{Anhang}\langen{Appendix}} %Den Anhang ohne Nummer zum Inhaltsverzeichnis hinzufügen`

Lösung ebenso mit einem Rückschritt bei der Aussteuerung der Sprachen...
`\addcontentsline{toc}{section}{Anhang} %Den Anhang ohne Nummer zum Inhaltsverzeichnis hinzufügen`

**Comment by u-fischer** [comment]
Das hier sollte helfen (nach hyperref)

~~~~
\makeatletter
\pdfstringdefDisableCommands{\let\selectlanguage\@gobble}
\makeatother
~~~~

Aber natürlich wäre es viel vernünftiger, wenn diese Template die Standardnamen \appendixname, \refname  usw und das normale babel interface verwenden würde.

**Comment by andygrunwald** [comment]
@u-fischer Danke!
Könntest du einen Pull Request machen?

**Comment by u-fischer** [comment]
@andygrunwald  Nein, dafür habe ich keine Zeit. N.B: luainputenc und T1-Encoding ist  nicht das richtige für lualatex. Entweder verwendet pdflatex oder stellt korrekt auf TU-encoding und Opentrype-Schriften um.

**Comment by ChristianLuxem** [comment]
@u-fischer ,
schade. Wir machen das alle hier in unserer Freizeit, auch wenn die meisten von uns schon lange mit dem Studium an der FOM fertig sind. Danke auf jedenfall für die Tipps, hier ist vieles über die jahre gewachsen, und sicher auch einiges eingespielt worden, welches einer Überarbeitung bedarft. 
@FelixKohlen  konntest du mit den Hinweisen etwas erreichen und magst du vielleicht dann einen Pull-Request aufmachen wenn es funktioniert?

**Comment by FelixKohlen** [comment]
@ChristianLuxem ich habe eine PR #158 erstellt. Auf den ersten Blick scheint der Tipp funktioniert zu haben.

**Comment by ChristianLuxem** [comment]
Danke @FelixKohlen ,
kannst du bite noch die englische Version kurz compilieren und testen ob es dort auch zu keinem FEhler kommt und die Datei dann ggf mit einchecken?
Danke
