### ISSUE TITLE
Fußnote ebd.

### ISSUE THREAD

**Issue by sharlinski** [andygrunwald/FOM-LaTeX-Template#151]
Hallo zusammen,

ich würde gerne in den Fußnoten automatisch ebd. verwenden. 
Ich hab es mit style=ext-authoryear-ibid probiert, allerdings ändert sich dann nichts.
Wenn ich style=authoryear-ibid mache bekomme ich folgende Fehlermeldung: 

Package xkeyval Error: `innamebeforetitle' undefined in families `blx@opt@pre'. \blx@processoptions
Command \jourvoldelim undefined. \renewcommand*{\jourvoldelim}

Kann mir da jemand helfen?

**Comment by delismen** [comment]
Das `style=ext-authoryear-ibid` passt schon.
Zusätzlich musst du das cite Makro in modsBiblatex2018.tex ganz am Ende anpassen:

`\renewbibmacro*{cite}{%
  \global\boolfalse{cbx:loccit}%
  \iffieldundef{shorthand}
    {\ifthenelse{\ifciteibid\AND\NOT\iffirstonpage}
      {\usebibmacro{cite:ibid}}
      {\ifthenelse{\ifnameundef{labelname}\OR\iffieldundef{labelyear}}
        {\usebibmacro{cite:label}%
         \setunit{\printdelim{nonameyeardelim}}}
        {\toggletrue{abx@bool@giveninits}
          \printnames[family-given]{labelname}%
          \setunit{\printdelim{nameyeardelim}}}%
        \printfield{usera}%
        \setunit{\printdelim{titleyeardelim}}% 
        \usebibmacro{cite:labeldate+extradate}}}
    {\usebibmacro{cite:shorthand}}}`

**Comment by frederikluettmann** [comment]
Hallo zusammen,

das Thema hat mich auch beschäftigt, danke für den richtigen Tipp @delismen!
Habe einen entsprechenden Pull Request gestellt:
https://github.com/andygrunwald/FOM-LaTeX-Template/pull/188
