### ISSUE TITLE
Fußnote bei Internetquellen anpassen

### ISSUE THREAD

**Issue by Servior85** [andygrunwald/FOM-LaTeX-Template#152]
Hallo zusammen,

ich möchte diese Vorlage nutzen um mein Scientific Essay und auch sonstige Arbeiten zu erstellen. Bisher klappt soweit alles ganz gut, bei der Nutzung von Fußnoten blicke ich allerdings noch nicht ganz durch.

Laut FOM Leitfaden sollen Internetquellen wie folgt aufgebaut sein:
Verfasser, (Stichwort, Erscheinungsjahr): Titel, (Erscheinungsdatum), <Internetadresse> (Datum) [Zugriffsdatum]

Gebe ich die Internetquellen mittels \footcite{...} an, so ist das Ergebnis nicht annähernd identisch zum geforderten. Stattdessen wird nur folgendes angezeigt:
Verfasser, Stichwort, Datum

Verwende ich stattdessen \footfullcite{..}, so wird die Fußnote nahezu identisch zum geforderten angezeigt. Einzige Unterschiede hierbei sind:
- Vor der URL wird noch die Kennzeichnung "URL:" angezeigt.
- Die Webadresse wird in einer komplett anderen Schriftart/Schriftgröße angezeigt.

Kann mir jemand sagen wo bzw. wie ich das anpassen kann, sodass die Kennzeichnung wegfällt und die URL identisch zur restlichen Fußnote ist?

**Comment by xremix** [comment]
@Servior85 sieh Dir doch mal #154 an, da sollte es behoben sein.

**Comment by Servior85** [comment]
@xremix damit klappt es, danke.
