### ISSUE TITLE
Fehler beim Übersetzen 

### ISSUE THREAD

**Issue by olgiHH** [andygrunwald/FOM-LaTeX-Template#153]
Hallo zusammen, 

ich schreibe gerade meine BA und habe die Vorlage runtergeladen. 
Ich kriege beim Übersetzen folgende Meldung: 

l.11955 \RequireBibliographyStyle{\blx@bbxfile}

Anbei auch ein Screenshot. 

Kann mir da bitte jemand weiterhelfen? 

Danke im Voraus 
<img width="510" alt="Console Pic " src="https://user-images.githubusercontent.com/66031166/83055950-dd606300-a054-11ea-8756-1163a42bfa35.png">

**Comment by ChristianLuxem** [comment]
Hallo @olgiHH ,
wir wissen nicht genau welche Pakete du installiert hast, daher empfehlen wir immer die Ausführung in einem Docker-Container. Dort sind immer alle nötigen Pakete installiert. 
Magst du es mal mit Docker versuchen oder aus der Anleitung nochmal alle Pakete installieren?

**Comment by SimonHaak** [comment]
Moin,
die interessante Fehlermeldung ist, dass der Style ext-authoryear nicht gefunden wird. Dafür muss das Paket biblatex-ext installiert sein, dass ist bei dir offensichtlich nicht der Fall.
Wenn ich das richtig sehe hast du dier 2016er Version von texlive instaliert. Ab 2017 sollte das Paket enthalten sein. Ein aktualisieren auf die neueste Version sollte dir also abhilfe schaffen.

**Comment by upelham** [comment]
Hi,
wie ist es möglich, in Overleaf die Arbeit auf englisch umzusetzen?
Danke schon mal vorab und Gruß
David

**Comment by Steffeeeen1234** [comment]
> Hi,
> wie ist es möglich, in Overleaf die Arbeit auf englisch umzusetzen?
> Danke schon mal vorab und Gruß
> David

Hey David,

evtl. hätte man dafür einen neuen Issue aufmachen können. Mich hat es aber auch interessiert und eigentlich ist es ziemlich einfach, wenn man sich die compile.sh mal angeschaut hat.... 

füge in der Datei "thesis_main.tex" die folgende Codezeile unterhalb von \documentclass[12pt,oneside,titlepage]{scrartcl} ein

`\def\FOMEN{}`

es sollte dann so aussehen:

`\documentclass[12pt,oneside,titlepage]{scrartcl}`
`\def\FOMEN{}`
`%Dokumentensprache`
`\newif\ifde`
`\newif\ifen`

Beim groben drüberschauen sah alles gut aus bei mir.

**Comment by upelham** [comment]
@Steffeeeen1234 ja, großen Dank dir!

**Comment by ChristianLuxem** [comment]
@olgiHH ,
ich nehme an das Problem ist mit einer neuen Tex-Version behoben worden, daher schließe ich das Issue erstmal. Solltest du weitere Probleme haben, kannst du das Ticket wieder öffnen.
