### ISSUE TITLE
thesis_english.pdf und thesis_main.pdf unterschiedlich

### ISSUE THREAD

**Issue by PascalThesing** [andygrunwald/FOM-LaTeX-Template#156]
Bei Aktuallisierungen sollte auch die thenis_english.pdf aktualisiert werden. Dadurch würden auch die Titelseiten ähnlicher aussehen und Fehler auffallen.

![image](https://user-images.githubusercontent.com/14017436/84601980-703a3380-ae84-11ea-8b8f-85f576629e35.png)
![image](https://user-images.githubusercontent.com/14017436/84601984-7cbe8c00-ae84-11ea-9484-f49a283f9b91.png)

**Comment by ChristianLuxem** [comment]
Vielen Dank @PascalThesing !
Ja leider wird die englische Version oft nicht beachtet. Die CI-Pipeline kontrolliert zwar, dass diese nach jedem Change noch fehlerfrei kompiliert werden kann, aber sie muss nicht aktualisiert hochgeladen werden. 
Wir könnten das zwar in einem Befehl immer beide Sachen ausführen lassen, aber dann würde auch der Kompilierungsprozess doppelt so lange dauern, und welcher Studierende hat während seiner Bachelorarbeit schon Zeit?

**Comment by PascalThesing** [comment]
Und was wäre wenn wir das Latex-Dokument über eine Pipeline bauen und als Artefakt speichern? Das sollte doch jetzt mit Github Actions funktionieren.

**Comment by xremix** [comment]
@PascalThesing das könnte für das Projekt hier funktionieren, nur würde es nicht für Anwender des Templates funktionieren, oder? Github Actions ist nur kostenlos, wenn es für Open Source Projekte verwendet wird und damit müsste jeder sein Projekt öffentlich machen. Oder sehe ich das falsch?

Ich habe / hatte bspw. immer private Repositories.

**Comment by PascalThesing** [comment]
@xremix Verhällt sich github actions nicht ähnlich Verhalten wie Travis?

**Comment by xremix** [comment]
Doch schon @PascalThesing , vielleicht habe ich hier auch nur etwas falsch verstanden. Hier die [Preisliste](https://github.com/pricing) und das sollte für das Repo hier an sich kein Problem sein.

Vielleicht könnte man ja auch (egal ob Travis oder Github Actions) vor dem Build die Checksumme speichern und die nach dem Build die Checksumme vergleichen, nachdem die Deutsche und Englisch Version gebuildet wurde. 
Wenn die Contributors hier mit Docker builden müsste die Checksumme ja gleich sein. Löst das dein Problem?

**Comment by PascalThesing** [comment]
@xremix dann müsste aber jeder beide Dokumente neu bauen. Durch das automatisierte Bauen und updaten, wäre dies nicht nötig.
