### ISSUE TITLE
Vorlage an die neuen FOM Richtlinien anpassen

### ISSUE THREAD

**Issue by Steffeeeen1234** [andygrunwald/FOM-LaTeX-Template#159]
Hallo zusammen,

in meiner Zeit an der FOM haben wir Andys Vorlage sehr intensiv für unsere Hausarbeiten und jetzt aktuell für unsere Masterarbeiten verwendet. Wir waren vier Leute die zusammen die Vorlage, leider nur lokal und nicht gleich hier in github, verbessert und an die FOM Richtlinien angepasst haben. 

Jetzt möchte ich den Schiefstand nachholen und nach und nach kleinere Verbesserungen aus meinem Projekt überführen, damit auch nachfolgende FOM Studierende davon profitieren und sich mehr auf die Forschung als auf die Formvorschriften konzentrieren können,

Ich denke das ist auch in eurem aller Interesse?
Die Änderungen werde ich dabei so allgemein wie möglich halten, damit es für viele funktioniert.

Aktuell bin ich aber noch dabei mich mit Github zurechtzufinden. Habe erst einmal das HelloWorld Projekt erledigt, die beiden verlinkten Seiten gelesen (Using pull requests, Creating a pull request) und schau mich hier jetzt ein wenig um. 

Ich denke als nächstes werde ich mir mal eine Kleinigkeit aus unserem Projekt raussuchen und hier einbinden. Habt ihr sonst noch ein paar Hinweise, die ich aus der README und aus der Vorlage-PDF nicht entnehmen konnte?

Gruß Steffen

**Comment by ChristianLuxem** [comment]
Hallo @Steffeeeen1234 ,
erstmal herzlich willkommen!
Wenn du Hilfe benötigst bei irgendwas, sag ruhig Bescheid. Jede Hilfe ist Willkommen und wir sind sehr dankbar dafür. 
Viel falsch machen kannst du nicht, die Pull-Requests müssen sowieso von einem Admin akzeptiert werden (mir oder Andy). Dabei wird auch automatisch überprüft, ob das PDF fehlerfrei gebaut werden kann. Wichtig wäre uns nur, dass du auch selbstständig die englische Variante kurz kontrollierst wenn du Änderungen im Text einbaust.

**Comment by andygrunwald** [comment]
Hey @Steffeeeen1234,

ich schließe mich an was @ChristianLuxem bereits geschrieben hab.

Was vorteilhaft wäre um die Changes schnell zu mergen:
- Pull Requests klein halten
- Am besten nur einen logisch zusammenhängenden Change pro Pull Request
- Kontext warum dieser Change notwendig ist, welches Problem er löst und was es ggf. für Seiten-Effekte/Folgen hat

Die Infos helfen uns das ganze schneller zu verstehen und führen zu einer schnelleren Übernahme in den master-branch.
Lass es uns wissen, falls wir helfen können.

Zum Thema Einarbeitung und Pull-Request:
Ich empfehle die exzellente GitHub-Dokumentation, speziell [Working with Pull Requests](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests).

**Comment by Steffeeeen1234** [comment]
Alles klar danke für die Hinweise. Bisher habe ich die Vorlage nur in overleaf verwendet. Ich werde aber mal schauen dass ich alles so einrichte wie ihr es in der Anleitung beschrieben habt. 

Ich freu mich schon auf die Zusammenarbeit:)

**Comment by Steffeeeen1234** [comment]
Hey @andygrunwald und @ChristianLuxem ich fühle mich mitlerweile bereit hier meinen Beitrag hinzuzufügen. Habe bereits ein wenig mit meinem HelloWorld Projekt geübt und möchte jetzt mal richtig loslegen. Allerdings kann ich mir keinen Branch anlegen/erzeugen. Funktioniert das bei euch anders oder habe ich keine Rechte dafür? Mir wird nicht die Möglichkeit angezeigt einen neuen Branch zu erzeugen ich kann lediglich nach bestehenden suchen.

Gruß Steffen

**Comment by ChristianLuxem** [comment]
Hallo @Steffeeeen1234,
deine Vermutung ist richtig, du musst zuerst einen Fork erstellen. Dann kannst du in deinem Fork einen neuen Branch anlegen und dann hier einen Pull-Request von deinem Fork auf unseren Master-Branch stellen. Den schaue ich mir dann an.
Du kannst dir gerne mal andere Pull-Requests ansehen, dann siehst du in etwa wie das abläuft, zum Beispiel: #161
Ich freue mich auf deinen ersten Pull-Request, vielen Dank für deine Mühe!

**Comment by Steffeeeen1234** [comment]
So erster PR ist fertig. Sieht aus als wenn ich es richtig gemacht habe. Mal schauenw as ihr für Feedback habt :)

**Comment by ChristianLuxem** [comment]
Danke habe ich angenommen. 
Ich schließe diesen Issue dann vorerst :)
