### ISSUE TITLE
Suffix vom Anhang wird in die Referenz übernommen

### ISSUE THREAD

**Issue by flowmymind** [andygrunwald/FOM-LaTeX-Template#163]
Hallo zusammen,
bin gerade in den finalen Zügen meiner Thesis und auf Fehlersuche. Da dies aber meine erste Arbeit mit Latex ist bin ich entsprechend Anfänger und finde auf die Schnelle keine Lösung.

Durch den neuen Code https://github.com/andygrunwald/FOM-LaTeX-Template/pull/147
https://github.com/andygrunwald/FOM-LaTeX-Template/blob/cab57e76cab0f1049d26799fc47319383226f482/thesis_main.tex#L333
https://github.com/andygrunwald/FOM-LaTeX-Template/blob/cab57e76cab0f1049d26799fc47319383226f482/thesis_main.tex#L334
wird der Doppelpunkt ":" auch in Verweisen `\ref{}` aufgeführt. Die Folge:

`Die Datengrundlage zur Beispielrechnung ist in Tabelle \ref{tbl:example} im \ref{exampleappandixsection} aufgeführt.`
`Die Datengrundlage zur Beispielrechnung ist in Tabelle 14 im Anhang 2: aufgeführt.`

Folgende Hinweise habe ich bereits entdeckt:
[https://tex.stackexchange.com/questions/68485/how-can-i-add-a-prefix-to-only-a-particular-section-levels-numbering](url)
[https://tex.stackexchange.com/questions/321205/prefix-for-section-headings-but-not-in-captions](url)
Allerdings geht es immer um das gesamte Dokument und nicht um spezielle Kapitel.

**Comment by Steffeeeen1234** [comment]
Hi @flowmymind,

ich bin auf diese beiden Artikel gestoßen:
https://tex.stackexchange.com/questions/257364/removing-the-trailing-period-when-referencing-a-section-number
https://tex.stackexchange.com/questions/125432/remove-period-when-cross-referencing-a-section

Beide sagen, dass die Lösung, die auch in dieser Vorlage verwendet wird, kein guter Style ist, wegen eben dem Problem welches du auch hast.

Ich habe ein bisschen rumgespielt und folgende Lösung entdeckt. Die Lösung ist glaube noch nicht perfekt aber sie funktioniert bei mir.

Die folgenden 3 Zeilen müssen in der thesis_main.tex im Anhangbereich eingefügt werden (siehe komplettes Beispiel unten)

\makeatletter
\renewcommand\@seccntformat[1]{\csname the#1\endcsname:\quad}
\makeatother

Außerdem müssen die Doppelpunkte hinter \arabic{subsection}:} und \arabic{section}:} entfernt werden.

Das sieht dann so aus

%-----------------------------------
% Anhang
%-----------------------------------
\newpage
\section*{Anhang} %Überschrift "Anhang", ohne Nummerierung
\addcontentsline{toc}{section}{\langde{Anhang}\langen{Appendix}} %Den Anhang ohne Nummer zum Inhaltsverzeichnis hinzufügen
\begin{appendices}
\makeatletter
\renewcommand\@seccntformat[1]{\csname the#1\endcsname:\quad}
\makeatother
\addtocontents{toc}{\protect\setcounter{tocdepth}{0}} %
	\renewcommand{\thesection}{\langde{Anhang}\langen{Appendix} \arabic{section}}
	\renewcommand\thesubsection{\langde{Anhang}\langen{Appendix} \arabic{section}.\arabic{subsection}}
	\input{kapitel/anhang/anhang}
\end{appendices}
\addtocontents{toc}{\protect\setcounter{tocdepth}{2}}


Beispiel aus dem Textteil:
![image](https://user-images.githubusercontent.com/34890799/86531773-65dbea00-bec4-11ea-8e43-ac67919d8512.png)

Und so sieht der Anhang aus:
![image](https://user-images.githubusercontent.com/34890799/86531778-72604280-bec4-11ea-9564-9330bd66131c.png)

Ich hoffe das hilft dir?

**Comment by flowmymind** [comment]
Hallo Steffen,
wenn der fehlende Backslash einfügt wird, funktioniert es wunderbar! Vielen Dank.

`\renewcommand**\**@seccntformat[1]{\csname the#1\endcsname:\quad}`

Gruß Flo

**Comment by Steffeeeen1234** [comment]
Danke für den Hinweis, Ich habe es oben berichtigt.
