### ISSUE TITLE
Einfacheres Ändern der Dokumentensprache

### ISSUE THREAD

**Issue by Steffeeeen1234** [andygrunwald/FOM-LaTeX-Template#164]
Aktuell ist es kompliziert die Dokumentensprache zu ändern, wenn man z. B. kein Docker nutzen kann oder das Projekt in Overleaf eingebunden hat. 

Da die Compile.sh unter anderem die Variable FOMEN definiert um die Dokumentensprache auf english zu setzen, habe ich gedacht, es wäre einfacher dies dierekt in die thesis_main.tex zu integrieren.

Durch das Einfügen dieser Codezeile `\def\FOMEN{}` wird es ermöglicht auch ohne das Ausführen der compile.sh die Sprache auf english zu ändern. Bzw. sie bleibt auf deutsch, wenn die Zeile auskommentiert ist.

Dies funktioniert hervorragend unter Windows ohne Docker und in Overleaf. Auch durch die die Ausührung der Compile.bat unter Windows kann somit eine englische Version der Arbeit erzeugt werden.

Oder gibt es etwas was dagegen spricht?

**Comment by ChristianLuxem** [comment]
Ist nun im Quellcode. Daher closed.
