### ISSUE TITLE
In der Vorlage geht die Verlinkung auf die Fußnoten nicht

### ISSUE THREAD

**Issue by Steffeeeen1234** [andygrunwald/FOM-LaTeX-Template#169]
Ich habe festgestellt, dass die Verlinkung auf die Fußnote nicht funktioniert. 

Beispiel:
Fährt man mit der Mouse über die hochgestellt 3 auf Seite 5, wird einem kein Klickoption angeboten. In größeren Arbeiten, wo ggf. 10 oder auch mehr Fußnoten existieren, ist es sinnvoll dass man direkt zur richtigen Fußnote springen kann.

Um dieses Verhalten zu ermöglichen, müssen lediglich einige Pakete und Codezeilen richtig Ausgerichtet werden. Praktischer Nebeneffekt ist, dass auch eine Warnmeldung weggekommen ist.

Das Ergebnis kann in der angehangenen Nacher-PDF nachvollzogen werden.

[FOM_LaTeX_Template_Nachher.pdf](https://github.com/andygrunwald/FOM-LaTeX-Template/files/4893231/FOM_LaTeX_Template_Nachher.pdf)

Zum Vergleich habe ich auch noch die Vorher-PDF angehangen

[FOM_LaTeX_Template_Vorher.pdf](https://github.com/andygrunwald/FOM-LaTeX-Template/files/4893240/FOM_LaTeX_Template_Vorher.pdf)

**Comment by ChristianLuxem** [comment]
Ist gemerged.

**Comment by frederikluettmann** [comment]
Hallo zusammen,

Der Pull Request #170 enthält folgenden Kommentar in der modsBiblatex2018.tex:

> %Aufgrund der Änderung bzgl des Issues 169 in der thesis_main.tex musste ich die Zeile auskommentieren. Konnte aber das Verhalten, dass die Fußnoten grün sind, im nachhinein nicht feststellen.

Ich glaube, dass das Verhalten, dass die Fussnoten grün sind, im Nachhinein nicht mehr festgestellt werden konnte, da die Verlinkung der Fussnoten auf die Einträge im Quellenverzeichnis nicht mehr funktionieren. Durch meinen Pull Request #188 funktionieren die Links teils wieder (unbeabsichtigt, bei ebd.). Habe daher noch einen fix für die grünen Fusszeilen eingebaut (citecolor=darkblack gemäss ). Für die defekte Verlinkung habe ich #189 aufgemacht. Bekomme das selber nicht auf die schnelle gefixt.
