### ISSUE TITLE
Mehrere Quellen des selben Autors

### ISSUE THREAD

**Issue by oelles** [andygrunwald/FOM-LaTeX-Template#172]
https://github.com/andygrunwald/FOM-LaTeX-Template/blob/e0752b452111b66948422f01c839c5a5b9c75f87/literatur/literatur.bib#L25

Hier sollte nur {Mobile Lösungen} als Stichwort eingetragen werden. Dann werden die Quellen korrekt in der Fußnote dargestellt.

**Comment by Steffeeeen1234** [comment]
Hast du einen Screenshot, was nicht richtig dargestellt wird?

**Comment by oelles** [comment]
Habe gerade eben nochmals den Text dazu gelesen. War doch richtig, sorry.
