### ISSUE TITLE
Deaktivieren der Stichworte Funktion

### ISSUE THREAD

**Issue by upelham** [andygrunwald/FOM-LaTeX-Template#173]
Ich würde gerne das Benutzen der Stichworte (usera im Literatur.bib File) deaktivieren, da mein Professor dies wünscht. 

Also statt
Dahl, Stephan (Social Media Marketing 3, 2018): Social Media Marketing - Theories and Applications, London: SAGE, 2018
Dahl, Stephan: Social Media Marketing - Theories and Applications, London: SAGE, 2018
und 
statt 
Vgl. Dahl,S., Social Media Marketing 3, 2018, S. 1.
Vgl. Dahl,S., Social Media Marketing - Theories and Applications, 2018, S. 1.

Kann mir hier jemand helfen?

Schon mal Danke :)

**Comment by stelim** [comment]
Auf den ersten Blick, sollte es reichen, wenn Du in der Datei **modsBiblatex2018.tex** 
die Zeile 125: `\printfield{usera}%)` deaktivierst.
```
\renewbibmacro*{date+extradate}{%
  \printtext[parens]{%
    \printfield{usera}%
    \setunit{\printdelim{titleyeardelim}}%
    \ifentrytype{online}
       {\setunit*{\addspace\addcomma\addspace}%
         \iffieldundef{year}
           {\bibstring{nodate}}
       {\printlabeldateextra}}%
       {\printlabeldateextra}}}
```

**Comment by upelham** [comment]
jap, das wars 👍
