### ISSUE TITLE
Fußnoten - Leitfaden 2015 - Anzahl der Autoren ändern

### ISSUE THREAD

**Issue by flirtysanchez** [andygrunwald/FOM-LaTeX-Template#174]
Hallo! 

Erst einmal vielen Dank an den Ersteller der Vorlage! Tolle Arbeit!

Aktuell hab ich noch das Problem, dass wenn ich die 2015 Vorlage verwende (hab hier die thesis_main dementsprechend kommentiert / auskommentiert) bei der Verwendung von 

**~\fullfootcite[Vgl. ][S. 1555]{vomBrocke.2009}**

die Darstellung nur mit dem **ersten Autor** ist:

**Vgl.  vom Brocke, Jan et al. (2009), S. 1555**

Ich hätte gerne die ersten beiden Autoren in der Fußzeile genannt.

Bei der Verwendung von **footcite** wird das Jahr leider nicht in runden Klammern angezeigt.

Danke!

**Comment by Steffeeeen1234** [comment]
Ist das eigentlich noch aktuell?
Warum möchtest du den erst nach zwei Autoren in der Fußzeile das et. al haben?

**Comment by SimonHaak** [comment]
Da die Nutzung von et al. nach zwei Autoren meinem Verständnis nach nicht dem alten Leitfaden entspricht und auf Steffens Nachfrage keine Antwort kam schließe ich das Issue hier.
Bitte ein neues Issue eröffnen, sollte das Thema nochmal akut werden.

Beste Grüße,
Simon
