### ISSUE TITLE
Formel- und Symbolverzeichnis

### ISSUE THREAD

**Issue by oelles** [andygrunwald/FOM-LaTeX-Template#179]
Servus,

leider habe ich 2 kleine Probleme beim Layout. Laut dem Leitfaden zur formalen Gestaltung von Seminar- und Abschlussarbeiten (Stand Februar 2018) muss man auch ein 
Formel- und Symbolverzeichnis anlegen. Leider muss ich ein paar Formeln einbinden. Das Einbinden und die Nummerierung 
klappt auch, jedoch wird kein Symbolverzeichnis angelegt.  
Die Formel habe ich wie folgt angelegt:
\begin{align}
	L_P{=} 10lg \cdot \frac{P}{1 mW}
\end{align}
Das andere Problem ist, ich möchte dir Rechenschritte pro Zeile zeigen. Ich bekomme das nicht hin. Nun habe ich dir Rechenschritte wie oben in eine eigene align Umgebung gepackt mit * also {align*}. Ist das korrekt so? Geht das auch anders?

VG
oelles

**Comment by Steffeeeen1234** [comment]
Hallo @oelles , 

hast du es eigentlich geschafft, dass das Formel- und Symbolverzeichnis angelegt und richtig formatiert wird?
In einer Version von vor ein paar Jahren gab es in der main_thesis.tex noch einen Eintrag zum Symbolverzeichnis. Aber den Gibt es anscheinend nicht mehr und ich habe es bei mir ohne großen Aufwand jetzt auch nicht mehr hinbekommen.

Aber wenn du es geschafft hast, das Formel- und Symbolverzeichnis richtig anzulegen, dann lass uns doch ein paar Beispiele hier oder eröffne einen Pullrequest, damit wir es hier aufnehmen können. 

Das hilft bestimmt auch den anderen.

**Comment by Steffeeeen1234** [comment]
Hallo @oelles 

ich habe die Funktion für die Generierung eines Symbolverzeichnis in das Latex Dokument aufgenommen. Als Grundlage habe ich die Quelle genommen.  Quelle: https://www.namsu.de/Extra/pakete/Listofsymbols.pdf

Bei dir fehlte einfach noch die Option, dass du deine Symbole irgendwo definierst. Durch meine Änderung gibt es nun die Datei SymbolDef.tex unter Skripte. In dieser Datei kannst du alle Symbole zentralseitig defineiren. Sobald du die definierten Symbole im Text verwendest, werden sie auch im Symbolverzeichnis aufgenommen.

Sobald der PR 181 gemergt ist, kannst du die Funktionalität nutzen. Vielleicht nimmst du dir die Zeit und reviewst meine Änderungen im PR 181?

Gruß Steffen

**Comment by Steffeeeen1234** [comment]
Also nachdem der PR #185 gemerged wurde stehen weitere Beispiele für Formeln und Symbole im Latex Dokument zur Verfügung. Auch das Literaturverzeichnis wurde angepasst, damit diese Punkte dort aufgeführt werden.

Es entspricht noch nicht ganz dem Leitfaden von 2018 aber immerhin etwas. Ich denke damit ist ein guter Anfang getan und jemand anderes kann übernehmen.

**Comment by SimonHaak** [comment]
Durch den PR #185 (Danke Steffen!) sehe ich keinen Grund mehr dieses Issue noch offen zu haben.
@Steffeeeen1234, @oelles wie seht ihr das?

**Comment by SimonHaak** [comment]
Hallo zusammen,
Keine Antwort nehme ich einfach mal als Bestätigung, dass das Issue zu kann.
Falls doch noch was ist: Gerne ein neues Issue aufmachen!

**Comment by oelles** [comment]
ack ;-)
