### ISSUE TITLE
Glossar im Inhaltsverzeichnis anzeigen

### ISSUE THREAD

**Issue by fom-wi-bosa** [andygrunwald/FOM-LaTeX-Template#190]
Es gibt inzwischen für den Fachbereich IT-Management einen nagelneuen Leitfaden für wissenschaftliche Arbeiten.
Dort steht bspw. auf Seite 12, daß u. a. der Glossar auch eingebunden werden muß im Inhaltsverzeichnis.
 
Ich habe im Template den folgenden, leider nicht funktionierenden Aufruf für das Einbinden des Glossars in das Inhaltsverzeichnis gefunden:
 
                \usepackage[toc]{glossaries}
 
Leider scheitert das Einbinden des Glossars in das Inhaltsverzeichnis auf diese Weise unter dem aktuellsten MacTeX.
 
Was jedoch funktioniert ist, wenn man ein Erweiterungspaket zum ‚glossaries‘-Modul installiert, welches ‚glossaries-extra‘ heißt.

Das Einbinden funktioniert nach der Installation des Pakets wie folgt:
 
                \usepackage[toc=true]{glossaries-extra}

Danach wird der Glossar wunderbar im Inhaltsverzeichnis angezeigt.
 
Ich bitte Sie bei Gelegenheit meinen Beitrag zu testen und evtl. in Ihr GitHub-Project mit aufzunehmen.

Besten Dank dafür.

**Comment by Steffeeeen1234** [comment]
Soll nur das Glossar im Inhaltsverzeichnis mit drin stehen oder auch das Abkürzungsverzeichnis, Tabellen, etc.?
Kannst du mal den neuen Leitfaden zur Verfügung stellen?

**Comment by fom-wi-bosa** [comment]
Eigentlich soll, wenn notwendig, alle von Dir erstellten Verzeichnisse ins Inhaltsverzeichnis mit hinein.

**Comment by fom-wi-bosa** [comment]
An welche E-Mail-Adresse darf ich Dir den aktuellen Leitfaden senden?

**Comment by andygrunwald** [comment]
@fom-wi-bosa  Gerne kannst du es an dieses Issue hängen.
Wenn du ein Kommentar verfasst, ist unten ein "upload" Feld. Einfach drauf klicken und PDF auswählen.

![Screen Shot 2021-01-04 at 14 51 56](https://user-images.githubusercontent.com/320064/103541905-687fc200-4e9c-11eb-90e1-720e90ba9d4a.png)

**Comment by fom-wi-bosa** [comment]
Bin mir ehrlich gesagt nicht sicher, ob da kein Copyright auf dem Dokument ist ...
Zwar sagt die Studienberatung telefonisch, dass man den Leitfaden einfach weitergeben kann, aber das war nur eine mündliche Auskunft.
Vielleicht bin ich ein wenig zu ängstlich ... aber ich möchte jetzt zum Schluss keinen dummen Fehler begehen.
Deshalb meine Vorsicht.

**Comment by andygrunwald** [comment]
Verstehe. Ich hab soeben mal eine E-Mail mit dieser Frage an studienberatung@fom.de (siehe https://www.fom.de/hochschulzentren/duisburg/studienberatung.html) versendet.
Ich melde mich, wenn ich mehr weiß.

**Comment by fom-wi-bosa** [comment]
Super und danke für Dein Verständnis 👍 .

**Comment by SimonHaak** [comment]
@fom-wi-bosa Magst du mir in der Zwischenzeit verraten wo der Leitfaden im Online Campus zu finden ist? Suche ich unter "Mein Institut" -> "Download Center" nach "Leitfaden" finde ich nur die Leitfadenversion von Mai 2020 (" Leitfaden zur formalen Gestaltung Seminar-/Abschlussarbeiten (Stand Mai 2020)" Dateiname "LeitfadenZurFormalenGestaltungSeminarAbschlussarbeiten_BCW_Stud_2020_04_29.pdf"). Diese Version stimmt aber wohl inhaltlich mit der von 2018, an der die Vorlage hier derzeit ausgerichtet ist, überein.

**Comment by fom-wi-bosa** [comment]
https://campus.bildungscentrum.de/nfcampus/news/News.do?action=show&objectid=117071244&n=5003

**Comment by fom-wi-bosa** [comment]
https://campus.bildungscentrum.de/nfcampus/dc/5119/Leitfaden_zur_formalen_Gestaltung_ITM_Version1.2.pdf

**Comment by fom-wi-bosa** [comment]
@SimonHaak : ... bedauerlicherweise ist der von Dir genannte Leitfaden (LeitfadenZurFormalenGestaltungSeminarAbschlussarbeiten_BCW_Stud_2020_04_29.pdf) m. E. sehr viel besser als der neue IT-Management-Leitfaden.

Ich empfehle einfach lediglich meinen Änderungsvorschlag bzgl. des Einbindens des Glossars mit einzupflegen (evtl. nur als Kommentar, wie es bisher mit dem 'glossaries'-Package auch schon ist) und vorerst mal nicht den neuen Leitfaden zu integrieren.
Der neue Leitfaden braucht m. E. noch SEHR VIEL Nacharbeit, weil er bedeutend weniger verständlich ist, als der von 2020_04_29.

**Comment by fom-wi-bosa** [comment]
@andygrunwald, @Steffeeeen1234, @SimonHaak : Danke Euch allen, dass Ihr an meiner Anfrage so engagiert arbeitet. Bin wirklich begeistert ! Liebe Grüße. Bojan

**Comment by andygrunwald** [comment]
Die Problematik verschieder Leitfäden wird doch immer wieder ersichtlich.
Ich sehe zwei Möglichkeiten:

1. Kommentare in die TeX-Vorlage
2. Eigene Abschnitte in der README

Kommentare in die TeX-Vorlage hat den Vorteil, dass dies direkt im Code ist und somit nicht vergessen wird.
Wie seht ihr das? @Steffeeeen1234, @SimonHaak @fom-wi-bosa @ChristianLuxem

**Comment by SimonHaak** [comment]
> Ich empfehle einfach lediglich meinen Änderungsvorschlag bzgl. des Einbindens des Glossars mit einzupflegen (evtl. nur als Kommentar, wie es bisher mit dem 'glossaries'-Package auch schon ist) und vorerst mal nicht den neuen Leitfaden zu integrieren.
> Der neue Leitfaden braucht m. E. noch SEHR VIEL Nacharbeit, weil er bedeutend weniger verständlich ist, als der von 2020_04_29.

Auf den ersten Blick scheint es mir gar keinen inhaltlichen Unterschied zu geben außer, dass viel mehr Freiheiten gelassen werden. Das wäre in Hinblick auf die TeX-Vorlage ja aber kein Problem. 

Hast du vielleicht sonst noch Beispiele was im IT-Management Leitfaden inhaltlich anders ist? Bereits im normalen Leitfaden wird erwähnt, dass "[...] mit Ausnahme der ehrenwörtlichen Erklärung, dem Titelblatt und dem Inhaltsverzeichnis  selbst – alle Bestandteile der  Arbeit [...]" im Inhaltsverzeichnis auftauchen sollten. **D.h. eigentlich müssten wir auch in der Vorlage hier auch die verschiedenen Verzeichnisse und das Glossar mit in das Inhaltsverzeichnis aufnehmen.**


> Die Problematik verschieder Leitfäden wird doch immer wieder ersichtlich.
> Ich sehe zwei Möglichkeiten:
> 
>     1. Kommentare in die TeX-Vorlage
> 
>     2. Eigene Abschnitte in der README
> 
> 
> Kommentare in die TeX-Vorlage hat den Vorteil, dass dies direkt im Code ist und somit nicht vergessen wird.

Ich persönlich finde eine Kombination der Möglichkeiten am besten. So haben wir es in anderen Fällen (z.B. neuer Leitfaden 2018 / englische Version) ja auch schon gehandhabt. Also in der Vorlage die ggf. notwendigen Änderungen mittels Kommentar kenntlich machen um das einbauen zu vereinfachen und außerdem in der README darauf hinweisen, dass es die weiteren Möglichkeiten bereits gibt und sie nur "aktiviert" werden müssen.

**Comment by ChristianLuxem** [comment]
Moin zusammen, 

wenn es Unterschiede geben sollte, bin ich ebenfalls dafür diese per Kommentar und in der README einzubringen. 
Am elegantesten wäre es natürlich, wenn wir ebenfalls eine programmatische Lösung finden (so wie beim kompilieren der englischen Version). Das kommt aber natürlich ganz darauf an, wie hoch der manuelle Aufwand beim Anpassen wäre. Wenn es bei einem Unterschied bleibt, dann ist eine Beschreibung und das manuelle anpassen sicherlich in Ordnung.
Werden die Unterschiede größer, sollten wir über etwas anderes nachdenken ( Fork, Branch oder Parameter beim Kompilieren).

**Comment by Steffeeeen1234** [comment]
Ich sehe das genauso wie es @SimonHaak hier sagt:
> Hast du vielleicht sonst noch Beispiele was im IT-Management Leitfaden inhaltlich anders ist? Bereits im normalen Leitfaden wird erwähnt, dass "[...] mit Ausnahme der ehrenwörtlichen Erklärung, dem Titelblatt und dem Inhaltsverzeichnis selbst – alle Bestandteile der Arbeit [...]" im Inhaltsverzeichnis auftauchen sollten. D.h. eigentlich müssten wir auch für den bisherigen Leitfaden die verschiedenen Verzeichnisse und das Glossar mit in das Inhaltsverzeichnis aufnehmen.

Es sollten **alle** Bestandteile im Inhaltsverzeichnis auftauchen. Irgendwie merkwürdig, dass dies nicht mehr der Fall ist, denn ich hatte es in meiner Masterarbeit auch noch so drin. Ich schau mal nach wodran es liegt, denn evtl. hat sich durch eine der letzten Änderungen hier ein Fehler eingeschlichen.

**Comment by Steffeeeen1234** [comment]
Wer lesen kann ist klar im Vorteil ;) 
>  Irgendwie merkwürdig, dass dies nicht mehr der Fall ist, denn ich hatte es in meiner Masterarbeit auch noch so drin

Gleich am Anfang der Main.Tex steht, wie das Abbildungs- und das Tabellenverzeichnis ein oder ausgeblendet wird. Es ist jetzt standardmäßig eingeblendet.

@fom-wi-bosa ich habe auch rausgefunden, wie das Package glossaries funktioniert. Du hast tatsächlich einen kleinen Fehler hier entdeckt.

![image](https://user-images.githubusercontent.com/34890799/103579465-a0a4f600-4ed8-11eb-9e77-d8e61236fc4c.png)
Quelle: http://tug.ctan.org/macros/latex/contrib/glossaries/glossaries-user.html

Ich füge auch ein paar Infos zur Readme hinzu, damit es verständlicher ist, wie die einzelnen Teile des Inhaltsverzeichnisses einfach verändert werden können. Der PR kommt gleich noch

**Comment by Steffeeeen1234** [comment]
PR ist fertig. Ich mach die nächsten Tage noch ein paar kleinere Schönheitsänderungen.
Wenn aber jemand Lust hat kann er/sie das Dokument mal auf englisch kompilieren und schauen ob die Texte im Inhaltsverzeichnis alle passen.

**Comment by Steffeeeen1234** [comment]
Ich habe noch ein paar Infos Punkte eingebaut auf die mich @ChristianLuxem hingewiesen hat.

Schönen Abend noch

**Comment by SimonHaak** [comment]
Da die Änderungen netterweise von @Steffeeeen1234 eingebaut wurden und auch die englischen Begriffe nochmal reviewed wurden schließe ich das Issue mal.
Sollte es doch noch Probleme mit dem Glossar geben bitte melden.
