### ISSUE TITLE
Willkommen @Steffeeeen1234 !

### ISSUE THREAD

**Issue by andygrunwald** [andygrunwald/FOM-LaTeX-Template#196]
Neuigkeiten, Neuigkeiten, Neuigkeiten!

Seit gestern ist @Steffeeeen1234 dem Projekt als offizieller Mitarbeiter beigetreten.

Steffen ist immer wieder positiv durch seine [Code-Contributions](https://github.com/andygrunwald/FOM-LaTeX-Template/pulls?q=is%3Apr+author%3ASteffeeeen1234+) und seine Hilfe in den Issues aufgefallen.
Wir freuen uns immer wieder wenn das Projekt durch kleine oder große Arbeiten besser wird und weitere Studenten unterstützt.

Vielen Dank fürs Mitmachen und ein dickes Danke für deinen bisherigen Effort!

Wenn Du Steffen in einem Issue siehst, Sag doch einfach mal Hallo (oder benutzen dieses Issue dafür) 🍻

PS: Wir werden dieses Thema nach "einiger" Zeit schließen - Es stellt kein Problem mit dem Projekt dar, ganz im Gegenteil.

**Comment by Steffeeeen1234** [comment]
Hey Andy,

vielen Dank. Dann kann ich ja jetzt meinen Lebenslauf auf LinkedIn anpassen 😃 
Seid wir im Studium die Vorlage gefunden hatten, habe ich gesagt: ich will da mithelfen und ich will die Vorlage verbessern. Hatte aber dann erst nachm Studium die Zeit meinen Beitrag zu leisten. Während des Studiums hatte ich mich nie mit GitHub beschäftigt. 

Ein paar Optimierungen werden von mir auch in den kommenden Monaten noch kommen. Je nach dem was die Zeit her gibt. 

Daher auch der Aufruf an alle Anderen, wenn ihr an einer Stelle eine Optimierungsmöglichkeit findet, versucht zu umzusetzen und erstelt einen Issue und am besten gleich einen PR hier auf Github (kein muss) aber teilt euer Wissen! Dadurch könnt ihr mithelfen, dass neben euch auch die anderen Studierenden etwas davon haben. Und ihr verbessert zumindest im Kleinen ein wenig die Welt.
