### ISSUE TITLE
Build Failing

### ISSUE THREAD

**Issue by Steffeeeen1234** [andygrunwald/FOM-LaTeX-Template#198]
Mir ist aufgefallen, dass Indikator "build" auf error steht.  

![image](https://user-images.githubusercontent.com/34890799/105085118-9c133c80-5a97-11eb-8f1f-9138fb9dcfff.png)

Auf der Seite https://travis-ci.org/github/andygrunwald/FOM-LaTeX-Template steht zwar warum das so ist aber ich bin mir nicht sicher wie man das beheben könnte.

**Comment by andygrunwald** [comment]
Generell sollten wir von TravisCI weg gehen, weil die immer weniger Open
Source unterstützen.

Ich schlage vor, dass wir nach GitHub Actions wechseln. Damit ist es näher
am Code und alles kann von jedem Contributer geändert werden.

Ggf. Kann ich die Tage mal einen PR machen.

Steffeeeen1234 <notifications@github.com> schrieb am Di. 19. Jan. 2021 um
20:48:

**Comment by ChristianLuxem** [comment]
@Steffeeeen1234 , 
bei mir steht der Build auf passed, sieht also gut aus. Das dauert nur manchmal einige Minuten.

**Comment by SimonHaak** [comment]
Bei mir steht aktuell noch (oder wieder?) "build error"
![grafik](https://user-images.githubusercontent.com/39888707/108111485-05856b80-7095-11eb-820d-0bf1039dff81.png)

Kennt sich jemand gut genug mit Github Action aus um den Vorschlag von @andygrunwald umzusetzen? Ansonsten sollten wir zumindest den Status aus der Readme nehmen. So sieht es ja sehr abschreckend aus.

**Comment by andygrunwald** [comment]
Mega, @SimonHaak!
Lass es mich wissen, wann der PR da ist und ich sehe zu, dass ich da sehr schnell drüber gucke, merge und TravisCI deaktiviere.

**Comment by SimonHaak** [comment]
Wie angekündigt habe ich auf Github Actions umgestellt. Dabei habe ich letztlich zwei Versionen entwickelt, weil mir die erste nicht gut genug gefallen hat:

1. Die, die aktuell in #203 sind. Eine Action, die einfach nur prüft ob der Compile durchläuft
2. Eine [erweiterte Version](https://github.com/SimonHaak/FOM-LaTeX-Template/tree/github-actions/.github/workflows), die letztlich aus drei Actions besteht:
- CheckDaily.yml - Kompiliert einmal täglich die deutsche und englische PDF um Probleme mit unseren Abhängigkeiten zu erkennen
- CheckPullrequest.yml - Kompiliert bei jedem Pull Request die deutsche und englische PDF und lädt sie als artifact hoch. Damit sehen die Personen die den Pull Request prüfen immer die richtige Version; Es kann nicht vergessen werden die aktualisierte PDF in beiden Sprachen hochzuladen
- CheckPush.yml - kompiliert bei jedem Push in den main branch beide PDFs und erstellt ein Release

Beide Varianten sind programmiert, interessant wären jetzt also eure Meinungen dazu welche Variante erstmal die bessere ist.

**Comment by andygrunwald** [comment]
Klingt erstmal super.
Ich finde die Funktionalität der drei versionen (Nightly, PR und Master/main-branch) super.

Wenn ich dies jedoch richtig beurteile, machen die drei yml für den eigentlichen schritt (compile) das gleiche.
Dadurch würde man sich ggf. unnötige Code Duplication reinholen, worunter die maintenance leiden kann (siehe compile.bat/compile.sh).

Eine Idee wäre, das ganze in einem Action-Workflow zu machen und mit `if` checks zu gucken, ob wir einen Step ausführen oder nicht. Siehe https://github.com/google/go-github/blob/master/.github/workflows/tests.yml#L28 als Beispiel.

**zB: (PseudoCode)**

On
- push <- Includiert PR sowie master branch
- schedule (nighthly)

Steps
1. Compile (das wäre CheckDaily.yml)
2. If is part of a PR -> Upload Artifact (das wäre CheckPullrequest.yml)
3. If branch == master -> Create Release (das wäre CheckPush.yml)

Was denkst du @SimonHaak ?

**Comment by SimonHaak** [comment]
Auf jeden Fall! Das ist ein guter und sinnvoller Vorschlag. Bin mit Github Actions ja nur noch nicht so bewandert.
Habe ich entsprechend deines Vorschlags umgesetzt und den Pull Request #205 erstellt.

**Comment by andygrunwald** [comment]
Super. Lass uns mal in #205 weiter sprechen.

**Comment by andygrunwald** [comment]
Das hier ist inzwischen gelöst. Dank geht an @SimonHaak
