### ISSUE TITLE
BibLaTex: Unterstützung des Types @legislation

### ISSUE THREAD

**Issue by mulchian** [andygrunwald/FOM-LaTeX-Template#200]
Hallo zusammen,

vielen Dank erstmal für die Vorlage, die funktioniert für meine ganzen Hausarbeiten sehr gut :)

Nun habe ich eine Hausarbeit bei der ich die Gesetzesentwürfe der EU zur Datenschutzgrundverordnung nutze.
Diese wird mir für die literatur.bib als Type "@legislation" definiert:
`@legislation{Schulz.2016,
  title = {Verordnung  ({{EU}})  2016/679  des {{Europäischen Parlaments}} und des {{Rates}} zum  {{Schutz}}  natürlicher  {{Personen}}  bei  der  {{Verarbeitung}}  personenbezogener  {{Daten}},  zum  freien  {{Datenverkehr}}  und  zur  {{Aufhebung}}  der  {{Richtlinie}}  95/46/{{EG}}  ({{Datenschutz}}-{{Grundverordnung}}): {{Datenschutz}}-{{Grundverordnung}} – {{DSGVO}}},
  shorttitle = {Datenschutz-{{Grundverordnung}} – {{DSGVO}}},
  date = {2016-04-27},
  journaltitle = {119},
  volume = {OJ L},
  url = {https://eur-lex.europa.eu/eli/reg/2016/679/oj},
  urldate = {2021-01-07},
  editora = {Schulz, Martin and Hennis-Plasschaert, Jeanine},
  editoratype = {collaborator},
  file = {C\:\\Users\\janni\\Zotero\\storage\\ABJW9JAM\\VERORDNUNG (EU) 2016-679 DES EUROPÄISCHEN PARLAMENTS UND DES RATES.pdf},
  number = {32016R0679},
  pagetotal = {88}
}` 

@legislation ist aber nicht in dem BibLaTex-Package enthalten.
Daher bekomme ich folgenden Fehler:
Package biblatex Warning: No driver for entry type 'legislation'.
(biblatex)                Using fallback driver on input line 451.

Besteht eine Möglichkeit @legislation und @jurisdiction zu unterstützen?

Falls nicht, muss sich mir einen alternativen Type suchen.

Danke und Gruß
Jannik

**Comment by SimonHaak** [comment]
Hallo Jannik,
wie soll es denn am Ende im Literaturverzeichnis aussehen? Vielleicht passt ja ein schon bestehender Typ dazu oder lässt sich von uns anpassen statt einen einen komplett neuen entry type zu definieren.

Beste Grüße,
Simon

**Comment by mulchian** [comment]
Hi Simon,
wie folgt sollte das im Literaturverzeichnis aussehen.

Europäisches Parlament (2014): Verordnung (EU) 2016/679 des Europäischen Parlaments und des Rates zum Schutz natürlicher Personen bei der Verarbeitung personenbezogener Daten, zum freien Datenverkehr und zur Aufhebung der Richtlinie 95/46/EG (Datenschutz-Grundverordnung – DSGVO) In: OJ L 119 vom 27.04.2016

[Author (Jahr): Titel (Kurztitel) In: volume journaltitle vom date]

Aktuell habe ich es als Internetquelle eingebunden, da ich es dort nachgelesen habe: (Hier mit den beiden Unterzeichnern statt dem Europäischen Parlament als Author)

Schulz, Martin, Hennis-Plasschaert, Jeanine (2016): Verordnung (EU) 2016/679 des Europäischen Parlaments und des Rates zum Schutz natürlicher Personen bei der Verarbeitung personenbezogener Daten, zum freien Datenverkehr und zur Aufhebung der Richtlinie 95/46/EG (Datenschutz-Grundverordnung): Datenschutz-Grundverordnung – DSGVO, <https://eur-lex.europa.eu/eli/reg/2016/679/oj> (2016-04-27) [Zugriff: 2021-01-07]

Das wäre für meine aktuelle Hausarbeit auch ausreichend.

**Comment by andygrunwald** [comment]
Hallo @mulchian,

Hast du inzwischen eine Lösung gefunden?
Wenn ja, würdest du diese hier mit der Community teilen oder sogar ggf. einen [Pull Request erstellen](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)?

**Comment by andygrunwald** [comment]
Hey @mulchian,
leider haben wir seit einem Monat keine Antwort erhalten. Deswegen schließe ich das Ticket mal.
Wenn du doch noch Feedback hast, einfach posten und wir öffnen das Ticket erneut.
Danke dir.

**Comment by mulchian** [comment]
Hi @andygrunwald,
entschuldige, dass ich bisher nicht geantwortet habe.
Leider habe ich keine passende Lösung für das Dokument gefunden und mich damals mit meinem Prof abgestimmt, dass es auch anders geht.
Daher kann das Issue geschlossen bleiben.

**Comment by andygrunwald** [comment]
@mulchian Danke dir.
Kannst du kurz sagen, was nun anders gemacht wurde, nach der Abstimmung mit deinem Prof?
Ggf. hilft es anderen.

**Comment by mulchian** [comment]
Im Leitfaden der FOM ist nicht genau erwähnt, wie man Verordnungen oder Richtlinien korrekt zitiert. Meiner Meinung nach war @legislation dafür die korrekte Art.
Aber nach Rücksprache werden Verordnungen und Richtlinien der EU genauso bzw. ähnlich wie Gesetze in Zitaten behandelt.
Sprich es gibt keinen Literaturhinweis sondern die Erwähnung erfolgt im Text. Es muss aber zu Beginn einmal der komplette Titel der Verordnung (Verordnung XY von XX.XX.XXX um XY Grund) aufgeführt werden.
Bei der ersten Verwendung kann die Verordnung also in der Fußnote voll aufgeführt werden. Soll diese erneut verwendet werden kann am Ende ein für die Verordnung übliches Kürzel angegeben werden und dieses bei weiteren Zitaten genutzt werden.

Beispiel für die DSGVO
erste Nutzung in der Fußnote:
Verordnung (EU) 2016/679 des Europäischen Parlaments und des Rates zum Schutz natürlicher Personen bei der Verarbeitung personenbezogener Daten, zum freien Datenverkehr und zur Aufhebung der Richtlinie 95/46/EG (Datenschutz-Grundverordnung): Datenschutz-Grundverordnung (ABI. L119/1 Art. XX) - DSGVO

weitere Nutzungen im Text oder Fußnote bei Vergleichen:
ABI. L119/1 Art. XX - DSGVO

Ich hoffe das hilft etwas weiter. Kann natürlich von Professor und Standort abweichen, aber im Grunde sollte es aufs Gleiche hinauslaufen.

**Comment by andygrunwald** [comment]
Danke @mulchian. Das hilft.
Viel Erfolg weiterhin.
