### ISSUE TITLE
Fehler beim kompilieren

### ISSUE THREAD

**Issue by Servior85** [andygrunwald/FOM-LaTeX-Template#201]
Hallo zusammen,

ich habe heute das Template neu heruntergeladen, da es seit meiner letzten Verwendung mehrere Änderungen gab. Beim kompilieren bekomme ich allerdings Fehler. Ich kompiliere das Template ohne jegliche Änderung, einfach nur die zip-Datei entpacken und die compile.bat starten.
Um Fehler an meiner Installation auszuschließen habe ich MikTex vollständig deinstalliert und die neuste Version heruntergeladen, sowie alle Updates installiert. Nachdem alle Packages installiert sind erhalte ich nun folgenden ersten Fehler (weitere Fehler werden vermutlich eine Folge davon sein):

! Undefined control sequence.
l.262 \AdaptNoteOpt
                 \footcite\multfootcite
?

Das Kommando soll wohl zum Package fncpt gehören, schaue ich mir die fncpt.sty an, finde ich dort allerdings nur das Kommando \AdaptNote und nicht das hier verwendete.

Jemand eine Idee wie ich die Kommandos reinnehme bzw. ob hier ggf. Anpassungen notwendig sind?

**Comment by SimonHaak** [comment]
Moin @Servior85 ,
spontane Vermutung: Schau mal nach ob MikTex das Paket biblatex-ext bei dir mitinstalliert hat. Falls nicht versuch das bitte einmal nachzuinstallieren.

Ansonsten: Kannst du vielleicht die gesamte Ausgabe einmal posten?

Ich habe gerade das Projekt nochmal heruntergeladen und die compile.bat ausgeführt. Beim ersten durchlauf kommt es zu ein paar erwartbaren Fehlermeldungen, weil noch Abhängigkeiten fehlen. Ab dem zweiten Durchlauf (der ja automatisch passiert, "lualatex thesis_main.tex" wird in der compile.bat drei Mal aufgerufen) gibt es bei mir keine Meldungen mehr.
Allerdings habe ich bei mir auch texlive 2019 und nicht miktex installiert.

**Comment by SimonHaak** [comment]
Hi @Servior85 ,
würdest du bitte einmal ausprobieren ob du das Template jetzt wieder kompilieren kannst? Mit #203 sollte der Fehler behoben sein.

Danke!

**Comment by Servior85** [comment]
Hi @SimonHaak,

ja, kann nun kompiliert werden. Bin mir allerdings nicht sicher ob die gewünschte Funktion dadurch nicht wieder verloren ist?
War der ursprüngliche Teil nicht dafür gedacht, dass bei mehreren Fußzeilen hintereinander ein Komma am Ende des einzelnen Eintrags gesetzt wird?

Das scheint jetzt nicht mehr zu funktionieren:
![image](https://user-images.githubusercontent.com/65962279/108505393-9b98dc00-72b7-11eb-8645-f1263bdb726f.png)

Ob dies vorher funktionierte kann ich nicht sagen, da ich es nicht compilieren kann.

Vielleicht habe habe ich die Funktion allerdings auch falsch verstanden :)
