### ISSUE TITLE
Abbildungs- und Tabellenverzeichnis - Fehlende Präfixe

### ISSUE THREAD

**Issue by fom-wi-bosa** [andygrunwald/FOM-LaTeX-Template#206]
Hallo liebes Entwicklerteam,

ich möchte Euch um eine Erweiterung des Templates hinsichtlich fehlender Präfixe im generierten Abbildungs- und Tabellenverzeichnis bitten.

Laut Leitfaden für Seminar- und Abschlussarbeiten (Stand Mai 2020, Seite 12) von den ProfessorInnen Jäger, Kümpel und Seng sollten die generierten Abbildungs- und Tabellenverzeichniseinträge jeweils einen Präfix je Eintrag enthalten.

Zum Beispiel soll vor dem Eintrag für die jeweilige Abbildung der String 'Abbildung' etc. automatisch eingefügt werden.
Die Vorlage fügt aber nur die laufende Nummer (1...n) ein.

Könnt Ihr hierfür evtl. bitte ein Lösung bereitstellen?

Ich habe es versucht, aber als LaTeX-Newbie dauert es einfach zu lange, bis ich eine Lösung habe, die vor allem in Euer Konzept passt.

Beste Grüße
Bojan

**Comment by Servior85** [comment]
Ich habe das bei mir wie folgt gelöst:

```
\usepackage[titles]{tocloft}
\renewcommand{\cftfigfont}{\langde{Abbildung}\langen{Figure} }
\renewcommand{\cfttabfont}{\langde{Tabelle}\langen{Table} }
```

Steht bei mir direkt vor dem `\begin{document}` in der thesis_main.tex

**Comment by fom-wi-bosa** [comment]
Vielen lieben Dank für die schnelle Hilfe und den sehr guten Lösungsvorschlag.
Funktioniert einwandfrei bei mir.
Beste Grüße

**Comment by Servior85** [comment]
#209 

Habe hierzu mal einen pullrequest erstellt. Hoffe das funktioniert so :)

**Comment by Smidelis** [comment]
Hallo, die KOMA-Script Klasse `scrartl` (welche hier genutzt ist) bietet diese Funktion selbst an. Man benötigt kein zusätzliches Paket.
```
\KOMAoption{listof}{entryprefix} %siehe KOMA-Script Doku v3.28 S.153
\BeforeStartingTOC[lof]{\renewcommand*\autodot{:}} %Für den Doppelpunkt hinter Abbildung
\BeforeStartingTOC[lot]{\renewcommand*\autodot{:}} %Für den Doppelpunkt hinter Tabelle
```

**Comment by andygrunwald** [comment]
@Smidelis Vielen Dank für die Info.
Wärst du so freundlich und würdest einen Pull Request erstellen? zB als Kommentar in die LaTeX Datei selbst oder in die README?
Ich denke, das würde einigen Leuten helfen.

**Comment by andygrunwald** [comment]
Gelöst in https://github.com/andygrunwald/FOM-LaTeX-Template/pull/212
