### ISSUE TITLE
Nighlty Build schlägt fehl

### ISSUE THREAD

**Issue by andygrunwald** [andygrunwald/FOM-LaTeX-Template#234]
Seit zwei Tagen schlägt der Nightly Build fehl.
Siehe https://github.com/andygrunwald/FOM-LaTeX-Template/actions/workflows/Check.yml

* Letzte erfolgreiche Ausführung: [Build #323 / 31th Dec 2021](https://github.com/andygrunwald/FOM-LaTeX-Template/actions/runs/1639430219).
* Erster Fehlschlag: [Build #324 / 1st Jan 2022](https://github.com/andygrunwald/FOM-LaTeX-Template/actions/runs/1642311437).

Es scheint sich etwas im Docker Image von X geeändert zu haben.
Die Sha-Summen sind anders.

Siehe letzter erfolgreicher run:
```
Pull down action image 'ghcr.io/xu-cheng/texlive-full:latest'
  /usr/bin/docker pull ghcr.io/xu-cheng/texlive-full:latest
  latest: Pulling from xu-cheng/texlive-full
  59bf1c3509f3: Pulling fs layer
  a470b0a41b48: Pulling fs layer
  59bf1c3509f3: Verifying Checksum
  59bf1c3509f3: Download complete
  59bf1c3509f3: Pull complete
  a470b0a41b48: Verifying Checksum
  a470b0a41b48: Download complete
  a470b0a41b48: Pull complete
  Digest: sha256:616a042db77b0380d2679e45296babd4adbb8e2ee192456b696efe92234ad783
  Status: Downloaded newer image for ghcr.io/xu-cheng/texlive-full:latest
  ghcr.io/xu-cheng/texlive-full:latest
```

Siehe erster fehlgeschlagener run:
```
Pull down action image 'ghcr.io/xu-cheng/texlive-full:latest'
  /usr/bin/docker pull ghcr.io/xu-cheng/texlive-full:latest
  latest: Pulling from xu-cheng/texlive-full
  59bf1c3509f3: Pulling fs layer
  2fc2b0eae0e1: Pulling fs layer
  59bf1c3509f3: Download complete
  59bf1c3509f3: Pull complete
  2fc2b0eae0e1: Verifying Checksum
  2fc2b0eae0e1: Download complete
  2fc2b0eae0e1: Pull complete
  Digest: sha256:267ed4411c4f48f04c3c6e1bd1fb125c57aa9487fa1753e0917afc26997047bd
  Status: Downloaded newer image for ghcr.io/xu-cheng/texlive-full:latest
  ghcr.io/xu-cheng/texlive-full:latest
```

**Comment by schroppae** [comment]
Ich hatte das Problem in meinem Fork (privat) eben auch:

Schritt: Compile LaTeX document (German)
Fehler: ` /bin/bash: line 1: ./compile.sh: Permission denied`

Lösung habe ich [in dieser Antwort gefunden](https://github.com/orgs/community/discussions/26239#discussioncomment-3250911)

Nach `git update-index --chmod=+x compile.sh` und Push ins Repository lief der Workflow durch und die PDFs wurden als Artefakte unter Releases abgelegt:
```
Output written on thesis_main.pdf (11 pages, 51033 bytes).
Transcript written on thesis_main.log.
PDF Compile: Success
```

Ich weiß noch nicht wie oder ob ich diese Lösung als Pull Request stellen kann, quasi ob GitHub die Berechtigungen übernimmt beim Pull Request. Aber vielleicht hilft der Kommentar zumindest anderen die vor dem gleichen Problem stehen.

**Comment by andygrunwald** [comment]
Der Build von heute Nacht lief durch: https://github.com/andygrunwald/FOM-LaTeX-Template/actions/runs/3325546175/jobs/5498343239

Aktuell kann ich diesen Fehler (den ich selbst reported habe) nicht reproduzieren.

**Comment by schroppae** [comment]
Ich habs auch nochmal mit einem öffentlichen Fork versucht, hier liefs auch erfolgreich durch.
Dann lag meine vermeintliche Reproduzierbarkeit wohl an einem Berechtigungsproblem beim Umzug in mein privates Repository, da hab ich dieses alte Issue wohl unnötig aufgestochert. Tut mir leid!

Trotzdem vielen Dank für die schnelle Reaktion und das tolle Projekt! 👍
