### ISSUE TITLE
Literaturverzeichnis ohne "Zugriff" für Nicht-Online Inhalte

### ISSUE THREAD

**Issue by lublak** [andygrunwald/FOM-LaTeX-Template#244]
Aktuell wird im normalem Literaturverzeichnis (nicht das Onlineliteraturverzeichnis) Zugriff angezeigt.
Bei Büchern ist dies eher unrelevant.
Gibt es eine Möglichkeit dies zu deaktivieren?
![image](https://user-images.githubusercontent.com/44057030/187455665-f8dd96ba-52ce-4d30-b8e8-ec9538bd0ff6.png)

**Comment by Smidelis** [comment]
Ich glaube ich hatte das Problem in der Vergangenheit auch schon. Versuche mal das Zugriff-Feld in deiner Software für die Bibliotheksverwaltung zu leeren. Das Feld brauchst du bei Büchern nicht.

**Comment by lublak** [comment]
@Smidelis da ich ein bisschen faul war und das bei jedem Eintrag zu ändern (Zotero packt diese Information automatisch mit rein wenn man Online ein Buch ließt) habe ich das im Pull Request #245 rausgenommen. Hier wird das dann nur bei den Online Literaturen verwendet. Für mich hat das dann super funktioniert :)
