### ISSUE TITLE
Frage: Github Workflow kein Access

### ISSUE THREAD

**Issue by D4sK43nguru** [andygrunwald/FOM-LaTeX-Template#257]
![image](https://github.com/andygrunwald/FOM-LaTeX-Template/assets/57450375/d70665cc-d2da-45e7-ad14-827f8885ec33)

Ich schreibe gerade im 2. Semester eine Seminararbeit. Ich kann die Arbeit über den Docker-Container kompilieren, die GitHub Integration/ der GitHub Workflow jedoch scheitert immer, wofür ich eine Mail bekomme. 

In den Logs zu dem Workflow finde ich in jedem Versuch die gleiche Meldung, dass der Workflow keinen Zugriff auf die ``./compile.sh`` hat.

Wie kann ich das am Besten umgehen/ beheben, dass GitHub die Datei auch kompilieren kann?

**Comment by andygrunwald** [comment]
@D4sK43nguru Hast du ggf. einen Link zum Workflow, damit ich mir das mal ansehen kann?
Bzw. hattest du die `compile.sh` abgeändert?

Die Builds in unserem Repo funktionieren nämlich wie erwartet: https://github.com/andygrunwald/FOM-LaTeX-Template/actions/runs/5262070679

Ich könnte mir vorstellen, dass das File nicht als executable markiert ist.

**Comment by D4sK43nguru** [comment]
Dies wäre der letzte ausgeführte Workflow, danach kamen noch welche aber die Meldung ist von Anfang an identisch.
https://github.com/D4sK43nguru/SeminararbeitSoSe2023/actions/runs/5265046074

**Comment by D4sK43nguru** [comment]
Ich habe in [diesem Issue](https://github.com/andygrunwald/FOM-LaTeX-Template/issues/234#issuecomment-1291119430) gelesen, dass das Problem schon mal auftrat. Ich versuch mal die da angegebene Lösung!

**Comment by D4sK43nguru** [comment]
Ja, jetzt funktioniert der Build. Ich bekam zwar diese Meldung

![image](https://github.com/andygrunwald/FOM-LaTeX-Template/assets/57450375/645065cc-4e28-44cf-b70a-ac03ad6ecba1)

das liegt aber vermute ich daran, dass ich zu dem Zeitpunkt noch keinen Release in dem Projekt hatte. Ich würde diesen Thread mit diesem Kommentar schließen.

**Comment by andygrunwald** [comment]
Top. Danke!
