### ISSUE TITLE
Translate README to english

### ISSUE THREAD

**Issue by andygrunwald** [andygrunwald/FOM-LaTeX-Template#27]
github is a world wide platform.
It make sense to translate the README to english

**Comment by markuspoerschke** [comment]
This template is for use at the FOM Hochschule only. So I think we can can keep this in German in my mind. -1

**Comment by chilian** [comment]
:-1:  I agree with markuspoerschke opinion. Other universities, countries etc. are using different styles, fonts or whatever.
Keep it simple and let's focus on a perfect FOM template.

**Comment by andygrunwald** [comment]
Okay. You are right. Thanks for your opinion :)
