### ISSUE TITLE
[WIP] Das Literaturverzeichnis muss römische Seitenzahlen haben

### ISSUE THREAD

**Issue by markuspoerschke** [andygrunwald/FOM-LaTeX-Template#3]
Das Literaturverzeichnis am Ende der Arbeit muss römische Seitenzahlen haben. Diese sind fortlaufend ausgehend von der letzen Seite der Verzeichnisse vor dem Inhaltsteil der Arbeit.

**Comment by andygrunwald** [comment]
@ChristianLuxem Weißt du zufällig ob das bei der FOM immer noch der Fall ist?

**Comment by florianbosten** [comment]
Hallo,
hier die Info aus dem formalen Leitfaden:
Mit Ausnahme des Titelblatts sind alle Seiten der Arbeit fortlaufend innerhalb der
oberen Kopfzeile zu nummerieren. Dabei sind, beginnend mit der ersten Seite
des Inhaltsverzeichnisses, sämtliche Verzeichnisse vor dem Textteil mit römischen
Ziffern fortlaufend durchzunummerieren. Beginnend mit der ersten Seite
des Textteils werden alle Seiten – mit Ausnahme der ehrenwörtlichen Erklärung
– mit arabischen Ziffern fortlaufend nummeriert (neu beginnend mit „1“)

**Comment by andygrunwald** [comment]
Danke @florianbosten!

**Comment by andygrunwald** [comment]
Das Literaturverzeichnis hat in der aktuellen Version römische Seitenzahlen. Siehe https://github.com/andygrunwald/FOM-LaTeX-Template/blob/master/thesis_main.pdf
