### ISSUE TITLE
Kann die modsBiblatex.tex nicht kompilieren

### ISSUE THREAD

**Issue by sebi5000** [andygrunwald/FOM-LaTeX-Template#30]
Hi,

erstmal vielen Dank für die tolle Arbeit. Ich glaube diese Vorlage erleichtert mir einiges. Allerdings kann ich die modsBiblatex.tex Datei nicht kompilieren. Ich nutze MikTex und als IDE Texmaker auf einem Windows 10 System. Muss ich irgendetwas besonderes installieren? Wenn ja wie?

![image](https://cloud.githubusercontent.com/assets/10114083/13858023/f5c4b4a4-ec7c-11e5-8976-01e7d087f47e.png)

Viele Dank.

**Comment by qpalym** [comment]
Hi,

ich bedanke mich auch für die Vorlage. Seit der letzten MikTex /Bibtex Version kann ich mein Projekt auch nicht mehr kompilieren. Ich habe das gleiche Problem wie sebi5000.

Vielen Dank

**Comment by qpalym** [comment]
Durch Ergänzen der folgenden Zeilen 
`\DeclareNameFormat{last-first}{%
  \nameparts{#1}%
  \iffirstinits
    {\usebibmacro{name:last-first}{\namepartfamily}{\namepartgiveni}{\namepartprefix}{\namepartsuffix}}
    {\usebibmacro{name:last-first}{\namepartfamily}{\namepartgiven}{\namepartprefix}{\namepartsuffix}}%
  \usebibmacro{name:andothers}}`


komme ich zwar weiter aber ich kenne mich viel zu wenig mit latex aus warum er dann andere Fehler wirft.

**Comment by andygrunwald** [comment]
@sebi5000 @qpalym Ich kann das Problem nachstellen.
Es muss wohl ein Breaking Change sein. Aktuell hab ich wenig Zeit mich darum aktiv zu kümmern.
Habt ihr bereits eine Lösung dafür? Wenn Ja, lasst mir diese zukommen und ich kann diese ein pflegen.

**Comment by Stylion** [comment]
Hallo zusammen,

ich habe auch die neuste MikTex Version 2.9 installiert und nutze den Texmaker
und kann das ganze auch nicht kompilieren... Ich würde gerne die Vorlage nutzen, kann mir da jemand weiterhelfen?
![unbenannt](https://cloud.githubusercontent.com/assets/18234852/14228297/dd44a86c-f910-11e5-9d46-44f7f07ae7b9.JPG)

**Comment by sebi5000** [comment]
Ich bin leider komplett neu in Latex und habe keine Ahnung was da passiert. Werde mich da erst mit beschäftigen müssen. Sobald ich etwas neues habe melde ich es. Falls ihr schon etwas mehr wisst her damit. Ich weiß nur das zumindest die meisten Fehler aus der Datei modsBiblatex.tex stammen.

**Comment by andygrunwald** [comment]
Hey,

die ersten Fehler mit `Illegal parameter number in definition of ...` habe ich in https://github.com/andygrunwald/FOM-LaTeX-Template/commit/7da02f1278c38cf7d447bcd05cb0a6f5fd243560 gefixt.
Ich habe das vor erst in einem Branch "latex-upgrade" comitted und merge das in den master, wenn die anderen Fehler auch gefixt sind.
Die Seite http://texwelt.de/wissen/fragen/16629/namensformat-mit-biblatex-33 hat mir dabei geholfen.

Die anderen Fehler stehen noch aus.

**Comment by Stylion** [comment]
Danke, dass du das nochmal fixed :)

**Comment by andygrunwald** [comment]
Kleines update.
Die ersten beiden Fixes habe ich in den master überführt (siehe https://github.com/andygrunwald/FOM-LaTeX-Template/commit/aadbb8c9836a8540396c56734b4cf354d1b183bc). Aktuell compiled die Vorlage leider noch nicht.
Aktuell ist meine Vermutung, dass es an https://github.com/andygrunwald/FOM-LaTeX-Template/blob/master/skripte/weitereEbene.tex liegt.

**Comment by Stylion** [comment]
Ok, ich warte weiterhin gespannt :)

**Comment by sebi5000** [comment]
Ja ich auch :). Tut mir auch echt leid das ich keine große Hilfe bin aber ich habe kein Plan. Habe schon selber versucht so eine Vorlage zu basteln, aber bekomme permanent Versionskonflikte mit Biblatex.

**Comment by Stylion** [comment]
Ist die Vorlage dann jetzt komplett ohne Fehler? :)

**Comment by latexuser** [comment]
Hallo Andy,

vielen dank für die großartige Arbeit bisher. Kannst du möglicherweise abschätzen, wann du als einziger Experte in diesem Gebiet dazu kommst dieses Template zu fixen?

Vielen Dank und Grüße

**Comment by Stylion** [comment]
Bitte bald :) ...sonst muss ich meine Hausarbeit in Word anfangen ^^

**Comment by Stylion** [comment]
![fehler](https://cloud.githubusercontent.com/assets/18234852/15022416/dac17140-122b-11e6-91cc-372e850ceac0.JPG)
Werden die Fehler noch behoben?

**Comment by andygrunwald** [comment]
Hallo zusammen,

es tut mir leid, dass dieses Problem bereits so lange existiert. Ich betreibe die ganze Sache in meiner Freizeit und bin seit einigen Jahren mit meinem Studium fertig. Dies ist der Grund warum ich nicht alles sofort lösen kann ;) Ich denke ihr versteht das.

Dennoch habe ich gerade das Problem behoben. Es lag an einer Inkompatibilität vom `titlesec` Paket und den KOMA-Skripten. Details findet ihr in https://github.com/andygrunwald/FOM-LaTeX-Template/commit/4622d29a998591912c6953099b3a259ff107cf66

Bei mir kompiliert das File nun wieder (mit Hilfe der `compile.sh`).

*Wichtige Änderung*: Falls Ihr den Befehl `\subsubsubsection` nutzt, muss dieser nun durch `\paragraph` ersetzt werden.

Auf den ersten Blick hat sich vom PDF nicht viel geändert. Aber bitte vergleicht es auch noch mal:

* [https://github.com/andygrunwald/FOM-LaTeX-Template/blob/3cc095a2078796a7109668efae4ca02244c29c29/thesis_main.pdf](Alte Version)
* [https://github.com/andygrunwald/FOM-LaTeX-Template/blob/master/thesis_main.pdf](Neue Version)

@sebi5000 @qpalym @Stylion @latexuser Bitte überführt die Änderungen in eure Arbeit und prüft ob diese nun kompiliert und noch viel wichtiger: *Gebt mehr Feedback*. Ein kurzer Post "Funktioniert jetzt", reicht. Oder ein Bier ;)

Viel Erfolg bei euren Arbeiten.

**Comment by Stylion** [comment]
Danke funktioniert... nur leider verschwindet das Literaturverzeichnis. Hast du da noch eine Idee :) ?
![unbenannt](https://cloud.githubusercontent.com/assets/18234852/15043960/9a386146-12d1-11e6-8fa8-908ffae54928.JPG)

**Comment by latexuser** [comment]
Hi Andy,

wiedermal vielen Dank! Ich habe soeben MikTex neu installiert und mit dem Master Branch alle Pakete neu installieren lassen.

Der erste Durchlauf lief fehlerfrei. Beim Biber Aufruf kommt danach folgende Fehlermeldung:

`
("C:\Program Files\MiKTeX 2.9\tex\generic\oberdiek\gettitlestring.sty"))
(thesis_main.out) (thesis_main.out)

Package biblatex Warning: File 'thesis_main.bbl' is wrong format version - expe
cted 2.6.

(thesis_main.bbl
! Use of \sortlist doesn't match its definition.
l.21   \sortlist{
                 nty}{nty}
?

`

**Comment by Stylion** [comment]
Ich kriege noch folgende Hinweise:
![unbenannt](https://cloud.githubusercontent.com/assets/18234852/15125054/32c653ee-162b-11e6-9fe7-d45a3f35165d.JPG)

**Comment by Stylion** [comment]
Kann jemand weiterhelfen? Habe auch extra alles neu installiert. Neuste MikTex und neuste TeXWorks. Beim kompilieren mit pdfLatex erhalte ich kein Fehler. Beim kompilieren mit BibLatex erhalte ich:
```
This is BibTeX, Version 0.99d (MiKTeX 2.9 64-bit)
The top-level auxiliary file: thesis_main.aux
I found no \citation commands---while reading file thesis_main.aux
I found no \bibdata command---while reading file thesis_main.aux
I found no \bibstyle command---while reading file thesis_main.aux
(There were 3 error messages)
```
Wenn ich die compile.bat nutze erhalte ich den gleichen Fehler wie @latexuser

**Comment by Stylion** [comment]
Kann jemand bitte helfen?

**Comment by latexuser** [comment]
HI Andy, kannst du bitte nochmal schauen ob du die richtige Version hochgeladen hast? @andygrunwald

**Comment by latexuser** [comment]
#push

**Comment by latexuser** [comment]
@andygrunwald Kannst du bitte nochmal drüber schauen? Es ist sicherlich nur eine Kleinigkeit für dich.

Viele Grüße

**Comment by andygrunwald** [comment]
Hallo @sebi5000, @qpalym, @Stylion, @latexuser,

ich hatte heute wieder etwas Zeit, habe alle ausstehenden Änderungen in das Projekt und das Problem ist inzwischen gelöst.
Welche Pakete auf einem Ubuntu 14.04-System benötigt werden könnt ihr in der [.travis.yml](./.travis.yml) oder im [Dockerfile](./Dockerfile) nachsehen.
Diese müsstet ihr eigentlich auch auf einem MacOSX oder Windows installiert bekommen.

Was ich euch aber ans Herz legen würde, ist das kompilieren mit Docker.
Das schafft alle Probleme direkt aus der Welt, weil es isoliert installiert und ausgeführt wird.
Wie das genau geht habe ich hier dokumentiert: https://github.com/andygrunwald/FOM-LaTeX-Template#docker-unter-linux--mac--windows

@latexuser & @Stylion: Schaut doch mal bitte ob das für euch funktioniert.
Mit der aktuellen Version im Repository funktioniert es tadellos.

**Comment by ChristianLuxem** [comment]
Hallo @andygrunwald,
ich habe es gerade getestet, ich kann bestätigen dass es mit Docker problemlos läuft. Nur eine Anmerkung checke ich gleich noch ein: In der Beschreibung sollte stehen, dass der Docker-Befehl in dem Ordner wo die Compile.sh liegt ausgeführt werden muss, ansonsten gibt es einen Fehler, dass die Compile.sh nicht gefunden wird ;) 
Ansonsten SUPER Arbeit! Das mit Docker ist gerade für Macs nützlich, hier hatte ich es bisher trotz einiger Kenntnisse noch nicht zum laufen bekommen. Danke dafür!

**Comment by andygrunwald** [comment]
Danke fürs Feedback @ChristianLuxem.
Hab deine Anmerkung gerade mal in https://github.com/andygrunwald/FOM-LaTeX-Template/commit/3d4a748effae337757ce21f41c4d4018d5d5a0cb hinzufügt.

Ich lasse das Ticket noch ein paar Tage offen und hoffe noch auf Feedback von @sebi5000, @qpalym, @Stylion, @latexuser, da die das Problem hauptsächlich hatten.

**Comment by andygrunwald** [comment]
10 Tage keine Antwort.
So wie es aussieht hat sich das ganze inzwischen erledigt und die Fehler sind behoben.
@koep und  @ChristianLuxem haben das ganze in den letzten Tagen auch noch mal ausgiebig auf Windows und Mac getestet.

Wenn jemand also noch mal Probleme hat, bitte ein neues Ticket aufmachen. Dann werde ich / wir uns drum kümmern. Danke euch und viel Erfolg noch mit euren Arbeiten.
