### ISSUE TITLE
Footcite Frage kein issue :)

### ISSUE THREAD

**Issue by cubasepp** [andygrunwald/FOM-LaTeX-Template#33]
Hallo,

erstmal fettes Mercie für die tolle Vorlage.
Ich bin iwie zu doof. Aber gibt's ne Möglichkeit die \footcite[Vgl. ][Setie X]{zit1} auf der Seite nochmal zu verwenden?

Sprich ich brauch am Anfang die Fußnote und am Ende nochmal. Will aber am Ende wieder auf Fußnote 1 referenzieren.

Ich finde keine Lösung.

Sorry das ich es hier rüber mache. Wollte dich da jetzt nicht mit ner EMail belästigen....

Thxi

**Comment by koep** [comment]
Angenommen dein
```latex
\footcite[Vgl. ][Setie X]{zit1}
```
erhält die Fußnote "6", dann kannst du mittels:
```latex
\footnotemark[6]
```
(leider manuell) darauf referenzieren.

Einen besseren Weg kenne ich nicht.

**Comment by cubasepp** [comment]
Okay Danke.
Habe ich mir fast gedacht. Das wird ganz schon ekelig. Da muss man übel aufpassen... :)

Vielen Dank für die schnelle Antwort!

**Comment by andygrunwald** [comment]
Super. Das war eine schnelle Antwort!
Ich close es mal. Sollte es doch nicht funktionieren, melde dich noch mal @cubasepp
