### ISSUE TITLE
Frage: Inhaltsverzeichnis

### ISSUE THREAD

**Issue by cubasepp** [andygrunwald/FOM-LaTeX-Template#36]
Hallo,

ich verzweifel gerade.
Beim Inhaltsverzeichnis hätte ich gerne:

1. Einleitung

1.1. Fragestellung

anstatt:

1 Einleitung
1.1 Fragestellung

Weiß jemand zufällig wie das geht? Der listof Parameter im Document ändert iwie nichts?!

Danke & Mercie

Michi

**Comment by andygrunwald** [comment]
Hey @cubasepp,

sorry für die späte Antwort. Bist du inzwischen auf die Antwort gekommen?
Wenn ich das richtig verstehe möchtest du den Text bündig haben, anstatt die Bezifferung.

Ich bin mir nicht sicher ob das so vom Leitfaden vorgesehen ist. Oder ist dies eine Anforderung vom Professor?
Es ist mit Sicherheit mit LaTeX möglich, jedoch würde es mich wundern, wenn es in der Standardausführung so mitgeliefert ist.

**Comment by andygrunwald** [comment]
Leider keine Antwort seit ca. 12 Tagen.
@cubasepp: Sollte deine Frage noch nicht beantwortet sein, lass es mich wissen und mach dieses Ticket wieder auf oder erstelle ein neues. In Ordnung?
Danke dir.

**Comment by cubasepp** [comment]
habe es nicht herausgefunden aber passt. habe es so abgegeben! :)

Konnte auch nicht früher antworten, Stress..

**Comment by andygrunwald** [comment]
Viel Erfolg für das Ergebnis!
