### ISSUE TITLE
Docker kompiliert nicht mehr

### ISSUE THREAD

**Issue by ChristianLuxem** [andygrunwald/FOM-LaTeX-Template#48]
Eigentlich müsste ich 2 Probleme melden...

1.) 
docker run -it --rm -v `pwd`:/data andygrunwald/fom-latex-template
Wenn man den Pfad kopiert, bekommt man sowohl unter Mac als auch unter Windows Probleme wegen den Anführungszeichen bei "pwd". Diese sollten weggelassen oder durch doppelte (") ersetzt werden.

Fehlermeldung: 
C:\Users\chris\FOM-LaTeX-Template-master>docker run -it --rm -v 'pwd':/data andygrunwald/fom-latex-template
docker: Error response from daemon: create 'pwd': "'pwd'" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed.
See 'docker run --help'.

2.) tritt bei Windows & Mac auf:

C:\Users\chris\FOM-LaTeX-Template-master>docker run -it --rm -v "pwd":/data andygrunwald/fom-latex-template
pdfTeX 3.14159265-2.6-1.40.17 (TeX Live 2016/Debian)
kpathsea version 6.2.2
Copyright 2016 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.21; using libpng 1.6.21
Compiled with zlib 1.2.8; using zlib 1.2.8
Compiled with poppler version 0.44.0
biber version: 2.5
/bin/sh: 1: ./compile.sh: not found
 

Ich hoffe du kannst das nachvollziehen unter Windows. Bin mir aber ziemlich sicher. Das ausführen einer Datei mit ./ macht man normalerweise nur bei Mac/Linux so. Für Windows sollte die .bat Datei ausgeführt werden und ohne ./ davor. Mich wundert es aber sowieso, dass anscheinend die Datei aus dem Verzeichnis gebraucht wird, anstatt die Datei in Docker verwendet wird? Oder liege ich hier falsch? Darauf schließe ich zumindest, weil man ja den Befehl in dem Ordner wo die compile Dateien liegen ausführen muss ( wie von mir beim letzten Change-Request beschrieben ).

**Comment by ChristianLuxem** [comment]
Muss mich korrigieren, jetzt funktioniert es auf meinem Mac auch nicht mehr. Gleiche Fehlermeldung.
Könnte am letzten Docker-Update liegen...

Docker-Version:
1.12.0-rc4

**Comment by ChristianLuxem** [comment]
Vielleicht hilft das hier weiter:
http://stackoverflow.com/questions/13702425/source-command-not-found-in-sh-shell

Ich verstehe leider noch Docker zu wenig, um ein paar Sachen auszuprobieren. Sowie ich das verstehe, ändert sich ja komplett gar nichts wenn ich das Dockerfile anpasse, weil der DockerContainer der ausgeführt wird ja in Github liegt und von dort gezogen wird, richtig?
Heißt, du müsstest dort etwas ändern und das würde dann bei jedem geändert werden oder?

**Comment by koep** [comment]
@ChristianLuxem: Ohne es getestet zu haben gehe ich davon aus, dass dein Windows / Mac das Kommando "pwd" nicht richtig interpretiert und somit den code nicht richtig in den container mounten kann.

Probier mal

```
docker run -it --rm -v C:\Users\chris\FOM-LaTeX-Template-master:/data
```

oder

```
docker run -it --rm -v "C:\Users\chris\FOM-LaTeX-Template-master":/data
```

Ich bin nicht sicher in wiefern Windows die Anführungszeichen benötigt.

> Ich verstehe leider noch Docker zu wenig, um ein paar Sachen auszuprobieren. Sowie ich das verstehe, ändert sich ja komplett gar nichts wenn ich das Dockerfile anpasse, weil der DockerContainer der ausgeführt wird ja in Github liegt und von dort gezogen wird, richtig?
Heißt, du müsstest dort etwas ändern und das würde dann bei jedem geändert werden oder?

Lese am Besten noch einmal den Unterschied zwischen einem container und einem image nach. 
Kurz gesagt: Der container ist ein laufender Prozess der das filesystem des images "sieht". Dieser wird lokal ausgeführt. Das image wird vor der Ausführung des containers vom docker hub heruntergeladen sofern es nicht lokal gebaut wurde. Mit Github hat das zunächst nichts zu tun. Da das image grundsätzlich funktioniert kann es fast nur an einem falschen "docker run" Kommando liegen.

**Comment by ChristianLuxem** [comment]
Hallo @koep , 
erstmal vielen Dank für deine ausführliche Antwort. 

Ich habe deine Vorschläge beide getestet, funktioniert leider trotzdem unter Windows nicht, ich teste morgen nochmal mit Mac.

Ich habe auch andere Sachen probiert, beispielsweise die Datei compile.sh in den Temp Ordner gelegt und probiert von da aus darauf zuzugreifen, funktioniert auch nicht. Jedesmal der selbe Fehler. 
Hab auch mal die Backslashes durch normale ersetzt, auch das tut es nicht. 
Kann es ein Berechtigungsproblem sein? Hab die Konsole auch mal als Admin ausgeführt, auch das bringt leider nichts...

Hast du noch eine andere Idee oder @andygrunwald ?

**Comment by ChristianLuxem** [comment]
@koep ,
ich habe es auf Mac hinbekommen.
Die Anleitung von der Docker-Seite lautet:

> If you are using Docker Machine on Mac or Windows, your Docker Engine daemon has only limited access to your OS X or Windows filesystem. Docker Machine tries to auto-share your /Users (OS X) or C:\Users (Windows) directory. So, you can mount files or directories on OS X using.
> 
> `docker run -v /Users/<path>:/<container path> ...`
> On Windows, mount directories using:
> 
>` docker run -v /c/Users/<path>:/<container path> ...`


 Quelle: https://docs.docker.com/engine/tutorials/dockervolumes/


 

Allerdings funktioniert das trotzdem nicht für Windows. Ihr könnt es gerne mal ausprobieren, aber wenn ich die Fehlermeldung google, komme ich immer wieder zu dem gleichen Eintrag auf Stackoverflow:
http://stackoverflow.com/questions/20635472/using-the-run-instruction-in-a-dockerfile-with-source-does-not-work

**Comment by koep** [comment]
Wie vermutet ist es ein Problem beim Client.

Du musst deinen docker daemon wie folgt konfigurieren (oder halt die entsprechende andere Partition freigeben):

![image](https://cloud.githubusercontent.com/assets/6319666/17108377/7c3aef54-5293-11e6-95e3-bd99f42820f0.png)

Danach funktioniert alles.

```powershell
PS C:\Users\cko\FOM-LaTeX-Template> docker run -it --rm -v ${PWD}:/data andygrunwald/fom-latex-template
```


Siehe auch: https://forums.docker.com/t/volume-mounts-in-windows-does-not-work/10693/99

**Comment by koep** [comment]
@andygrunwald Ich kann die Dokumentation gerne anpassen.
- Konfiguration des Docker daemon unter Windows 10 
- Separates docker run command für Windows (dort funktionieren `pwd` bzw $PWD nicht. Nur ${PWD}.

**Comment by andygrunwald** [comment]
Das wäre klasse, wenn du mir einen PR fertig machen könntest. Gerne auch
mit Link auf dieses Issue.
Danke Christian!

Am Montag, 25. Juli 2016 schrieb Christian :

**Comment by ChristianLuxem** [comment]
Hallo @koep ,

das mit PWD scheint bei mir immer noch nicht zu funktionieren:

```
C:\Users\chris\FOM-LaTeX-Template-master> docker run -it --rm -v ${PWD}:/data andygrunwald/fom-latex-template
docker: Error response from daemon: create ${PWD}: "${PWD}" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed.
See 'docker run --help'.

```
Wenn ich jedoch den Pfad einfüge, dann kompiliert es. Vielen Dank für deine Mühe! Es war wohl tatsächlich das Setting zum Pfad mounten...

Also der funktionierende Befehl bei mir unter Windows lautet:
`docker run -it --rm -v /c/Users/FOM-LaTeX-Template-master:/data andygrunwald/fom-latex-template`

**Comment by ChristianLuxem** [comment]
@koep 
ich war auch mal so frech mir dein Image runterzuladen und damit zu kompilieren. Funktioniert zwar auch mit dem Kompilieren, allerdings werden Fehler geworfen und das Inhaltsverzeichnis nicht erstellt. (Zumindest auf Windows)

Code für Windows:
`#!/bin/sh
docker run -i -t -w /mnt -v /c/Users/chris/FOM-LaTeX-Template-master:/mnt koep/texlive /bin/bash -c "./compile.sh"`
Code für Mac:
`#!/bin/sh
sudo docker run -i -t -w '/mnt' -v /Users/chris/FOM-LaTeX-Template:/mnt koep/texlive /bin/bash -c './compile.sh'
`

**Comment by ChristianLuxem** [comment]
@andygrunwald wenn du die Sachen in den Master-Branch übernommen hast, kann für mich dann das Ticket geschlossen werden..

**Comment by koep** [comment]
Das Problem mit $PWD liegt vermutlich daran, dass du die cmd.exe anstatt der powershell.exe verwendest.

**Comment by andygrunwald** [comment]
Hey Christian und Christian,

erstmal danke, dass ihr euch gegenseitig geholfen habt. Mich freut das ganze sehr, weil genau das hier für mich Open Source ist. Jemand veröffentlicht etwas, andere können es benutzen und profitieren ggf. davon und falls ein Problem auftritt hilft die Community sich auch selbst. Denn ab und zu kann der Projektautor nicht so schnell reagieren. Das ganze bringt mich zum lächeln :)
Danke dafür!

Zum Issue:
`pwd` ist ein Unix Befehl der das aktuelle Directory ausgibt. Siehe https://de.wikipedia.org/wiki/Pwd_(Unix)
Backticks "`" können innerhalb von Strings / Commands verwendet werden um einen weiteren Befehl auszuführen und das Ergebnis darin einzubetten. Wie in 
    
    docker run ... `pwd`....

Das Volume (Projektdirectory) wird innerhalb des Containers benötigt, weil wir die aktuellste Datei (compile.sh) ausführen wollten.
Da die compile.sh Teil des Projektes hier ist, möchte ich die ungern beim Bauen des Docker-Images in den Container laden. Weil das würde bedeuten, ich müsste das Docker-Image dauerhaft updaten, wenn das compile.sh-Skript geupdated wird.
Außerdem erlaubt uns das Volume das kompilierte Ergebnis (das PDF) zurück auf die Host-Datei zu spielen.

Und auch wenn wir unter Windows sind, wird die compile.sh (für Linux / Mac) ausgeführt, weil wir in der ersten Zeile des Dockerfiles sagen, dass wir auf einer Linux-Distribution laufen werden.

@ChristianLuxem Wenn du viel mit Software (Entwicklung, Nutzung, Research, Experimentieren) oder Infrastruktur (Software unter gegebenen Bedingungen / Servern laufen zu lassen) zu tun hast und du dich noch nicht mit Docker aus kennst, kann ich dir das nur ans Herz legen.
Kann ggf. einige Probleme aus der Welt schaffen. Für manche Arbeitsbereiche eine große Erleichterung. Ich nutze es hauptsächlich im continuous integration Bereich und zur Generierung von Dokumenten (LaTeX, API-Docs, etc.) oder zum automatischen testen einer REST-API. Siehe https://github.com/andygrunwald/simple-webserver#api-blueprint-validating-api-description für ein Beispiel.

Zurück zum Issue:
Wenn ich das richtig sehe, funktioniert nun alles bei euch, richtig? @koep? @ChristianLuxem?
Wenn nicht macht ein neues Issue auf und verlinkt dieses hier.
Danke euch beiden!
