### ISSUE TITLE
Zitierstil und Bibliografiestil abweichend?  

### ISSUE THREAD

**Issue by CDixi** [andygrunwald/FOM-LaTeX-Template#52]
Hallo, 

du nutzt als Zitierstil (Fußnote) "outhoryear" 
und als Bibliografiestil (Literaturverzeichnis) "numeric" 
(s. in der Datei thesis_aimn.tex unter" % Biblatex"). 

Meiner Meinung nach ist dies inkonsequent und müsste von den Profs auch schon bemängelt worden sein. Zumindest wurde es bei meiner letzten Hausarbeit bemängelt. Gibt es dafür einen speziellen Grund? Gab es da vielleicht mal ein Leitfaden von der FOM, der mittlerweile veraltet ist? 
Sowohl im Leitfaden Stand Februar 2015 und auch Stand 18.07.2016 wird ein "outhoryer" Stil für den Zitierstil und Bibliografiestil empfohlen.

**Comment by andygrunwald** [comment]
@CDixi Hey, danke für die Frage.

Einen speziellen Grund dafür nicht. Wenn ich mich recht erinnere stand in dem damaligen FOM-Leitfaden (~2013 / 2014) noch gar nichts in Bezug auf LaTeX drin.
Bei meinen Seminararbeiten sowie bei 4 Bachelor-Arbeiten (meine + Kollegen) wurde dies (meines Wissens nach) nicht bemängelt (Standort Düsseldorf).

Wenn du eine konsequentere Lösung kennst oder deine Lösung dem aktuellen Leitfaden entspricht, würde ich mich sehr über einen Pull Request freuen.
Wie das geht ist hier beschrieben: https://help.github.com/articles/creating-a-pull-request/

**Comment by andygrunwald** [comment]
Leider gab es seit 12 Tagen kein Feedback. Deswegen schließe ich das ganze hier mal.
