### ISSUE TITLE
Noch auf aktuellem Stand nach Leitfaden Version vom 18.07.2016?

### ISSUE THREAD

**Issue by Noirde** [andygrunwald/FOM-LaTeX-Template#53]
Hallo zusammen,

hat schon jemand geprüft ob das Dokument noch die aktuellen Ansprüche erfüllt?

Auszugsweise die Punkte bei denen ich mir unsicher bin:

**Schriftgrad und Zeilenabstand:** 
- Zeilenabstand im Text: 1,5-zeilig, Schriftgrad 12 pt (Times New Roman)
- Da viele verschiedene Schrifttypen existieren, ist die Wahl des Schriftgrads der diversen Schrifttypen an diese Vorgabe anzupassen (z. B. Arial in 11,5 pt), sodass immer ungefähr 37 Zeilen mit je ungefähr 60 Zeichen bzw. 2.200 Zeichen pro Seite erreicht werden. Die Abstände im Text vor einem Absatz sind mit 0 pt und nach einem Absatz bei 6 pt als Grundeinstellung vorzunehmen
- Der Zeilenabstand bei Überschriften soll vor einem Absatz 12 pt und nach einem Absatz 6 pt betragen.
- Zeilenabstand in Fußnoten einzeilig, Schriftgrad 10 pt (Times New Roman)

- Abstand des Textes vom Rand sollte sich an folgenden Richtwerten orientieren: 
a. Oben: 4 cm, Seitenzahl steht 2 cm von der oberen Papierkante 
b. Unten: 2 cm (letzte Zeile der letzten Fußnote bis untere Papierkante) 
c. Links: 4 cm 
d. Rechts: 2 cm  

- Mit Ausnahme des Titelblatts sind alle Seiten der Arbeit fortlaufend innerhalb der oberen Kopfzeile zu nummerieren. Die Seitenzahlen stehen zwischen zwei Strichen.14 Sollten die Kopfzeilen nicht mit den Kapitelnamen beschriftet sein, empfiehlt es sich die Seitenzahlen mittig darzustellen (1 cm rechts von der geometrischen Mitte). Dabei sind, beginnend mit der ersten Seite des Inhaltsverzeichnisses, sämtliche Verzeichnisse vor dem Textteil mit römischen Ziffern fortlaufend durchzunummerieren.15 D. h., dass das Titelblatt mitgezählt wird. Es erhält jedoch keine Seitenzahl. Das Inhaltsverzeichnis erhält als erste Seitenzahl mithin die römische Zahl II. Beginnend mit der ersten Seite des Textteils werden alle Seiten – mit Ausnahme der eidesstattlichen Erklärung16 – mit arabischen Ziffern fortlaufend nummeriert (neu beginnend mit „1“)

Ebenfalls entspricht das Literaturverzeichnis meines Erachtens nach nicht mehr den Vorgaben.

Die Eidesstattliche Erklärung hat sich in ihrem Aufbau ebenfalls leicht verändert.
Dokument habe ich beigefügt.
[Leitfaden_zur_formalen_Gestaltung_von_Seminar_und_Abschlussarbeiten_ Stand_18-07-2016.pdf](https://github.com/andygrunwald/FOM-LaTeX-Template/files/613500/Leitfaden_zur_formalen_Gestaltung_von_Seminar_und_Abschlussarbeiten_.Stand_18-07-2016.pdf)

**Comment by andygrunwald** [comment]
Hallo @Noirde,

diese Vorlage wird mit hoher Wahrscheinlichkeit nicht dem Stand vom 18.07.2016 entsprechen.
Ich habe diese Vorlage mit dem Stand von Mitte 2014 / Ende 2014 erstellt, weil ich zu dieser Zeit meinen Abschluss gemacht habe.

Ich benutze dieses Projekt nicht mehr aktiv. Weiterhin habe ich leider keine Zeit dazu, dies auf den aktuellen Stand zu bringen. Freue mich jedoch über jeden Pull Request.
Wenn du die Vorlage auf den aktuellen Stand bringen möchtest,  bist du gerne Willkommen :)

**Comment by teiling88** [comment]
@Noirde - ich nutze die Vorlage aktuell auch und passe diese an die aktuellen Gegebenheiten an. Wenn Du noch nicht an einem Pull Request arbeitest - erstelle ich einen.

**Comment by andygrunwald** [comment]
@teiling88 Gerne würde ich einen PR dazu mergen. Wenn du fragen hast, melde dich :)

**Comment by teiling88** [comment]
@Noirde 
> Die Eidesstattliche Erklärung hat sich in ihrem Aufbau ebenfalls leicht verändert.
Wo den? Oder bin ich blind? :-\

Bezüglich der Schriften und Abstände scheinen das die noch konformen zu sein wenn ich das richtig sehe. Lasse das aber noch mal prüfen.

**Comment by georg90** [comment]
Also passen auch Schriftart, Zeilenabstände etc. für den neuen Standard? Der PR passt ja nur die Seitenzahl an ;)

Vielen Dank für die super Vorlage!

**Comment by teiling88** [comment]
Ich habe dazu keine widersprüchliche Antwort mehr bekommen.

**Comment by georg90** [comment]
perfekt, dann closen?

**Comment by andygrunwald** [comment]
Euer Wunsch ist mein Befehl @georg90 @teiling88 :)
Danke euch beiden

**Comment by bhaertel** [comment]
Die Änderungen gehen auch noch über die oben diskutierten Anpassungen hinaus. Zudem gibt es schon wieder eine aktualisierte Version des Leitfadens vom 20.12.2016:
[Leitfaden_zur_formalen_Gestaltung_von_Seminar_und_Abschlussarbeiten_ Stand_20.12.2016.pdf](https://github.com/andygrunwald/FOM-LaTeX-Template/files/691423/Leitfaden_zur_formalen_Gestaltung_von_Seminar_und_Abschlussarbeiten_.Stand_20.12.2016.pdf)

Beispielsweise haben sich auch die Fußnoten geändert (Autor, Stichwort, Jahr ohne Klammern):
![image](https://cloud.githubusercontent.com/assets/24973449/21741079/2409e86a-d4cc-11e6-8ebd-a92dd18dc500.png)

Beim Literaturverzeichnis hat such auch einiges getan (keine Nummerierung, nach erster Zeile eingerückt, kein Punkt am Ende..):
![image](https://cloud.githubusercontent.com/assets/24973449/21741102/c3182eee-d4cc-11e6-8f0b-e814a12b1e56.png)

Beispiel:
![image](https://cloud.githubusercontent.com/assets/24973449/21741064/af376fb2-d4cb-11e6-8d20-3de42544f240.png)

Hat sich das evtl. schon mal jemand angeschaut? Leider fehlen mir hier die notwendigen Skills, um die notwendigen Anpassungen vorzunehmen :(

**Comment by teiling88** [comment]
Hier kannst Du die Fußnoten und Literaturverzeichnis anpassen: https://github.com/andygrunwald/FOM-LaTeX-Template/blob/master/skripte/modsBiblatex.tex

Die Datei ist so gut dokumentiert das Du dich dort schon zurecht finden solltest.

**Comment by andygrunwald** [comment]
Ich glaub hier ist alles geklärt.
Sollten doch noch Fragen aufkommen, bitte melden :)

**Comment by Zerster** [comment]
Ich stehe aktuell auch vor dem Problem, dass die Vorlage nicht den aktuellen Vorgaben entspricht. Ich bin gerade dabei, mich soweit einzuarbeiten, dass ich es selbst ändern kann. Über Unterstützung würde ich mich aber trotzdem freuen, ich bin blutiger Anfänger. :)

**Comment by andygrunwald** [comment]
@Zerster Wenn du soweit bist, würde ich mich über Pull Requests zur Verbesserung / Anpassung freuen.

Ich selbst studiere leider nicht mehr und nutze diese Vorlage somit auch nicht mehr. Stelle diese aber gerne für andere zur freien Nutzung zu Verfügung. Als Basis für weitere Modifikationen.
Wenn ihr euch die Arbeit machen wollt / könnt, diese auf den aktuellen Stand zu bringen, würde ich das auch mergen.
