### ISSUE TITLE
MDWList Paket

### ISSUE THREAD

**Issue by jumpRun** [andygrunwald/FOM-LaTeX-Template#54]
Hey, ich checke grade die Pakete durch und habe gesehen das das MDWList Paket zur Kontroller der drei Listenumgebungen itemize, enumerate, description mittlerweile durch enumitem ersetzt werden sollte.

https://www.ctan.org/pkg/mdwlist
The pack­age is part of the mdw­tools bun­dle; it is su­per­seded by en­u­mitem, which is to be pre­ferred for new work. 
https://www.ctan.org/pkg/enumitem
 It su­per­sedes both enu­mer­ate and md­wlist (pro­vid­ing well-struc­tured re­place­ments for all their fun­tion­al­ity), and in ad­di­tion pro­vides func­tions to com­pute the lay­out of la­bels, and to ‘clone’ the stan­dard en­vi­ron­ments, to cre­ate new en­vi­ron­ments with coun­ters of their own.

Ich habe bei einem kleinen Test keine Fehler feststellen können.

Gruß Freddy

**Comment by andygrunwald** [comment]
Wenn das die offizielle Dokumentation empfiehlt, sollten wir hier den Best Practices folgen.
Klingt nach einer guten Änderungg. Machst du einen PR dafür?
