### ISSUE TITLE
\usepackage{times} und {matptmx} BEIDE vorhanden

### ISSUE THREAD

**Issue by jumpRun** [andygrunwald/FOM-LaTeX-Template#55]
Hallo zusammen,

Im Dokument sind BEIDE Pakete vorhanden.
Laut CTAN und sonstiger Recherche ist das Paket TIMES mittlerweile obsolet. Zudem scheint es das MATHPTMX paket zu übersteuern. Die Reihenfolge der Pakete ist dabei ebenfalls egal.

Die Schrift wirkt mit MATHPTMX etwas schmäler als mit TIMES (bzw. wenn beide aktiviert sind.)

https://www.ctan.org/pkg/times
> The pack­age is now ob­so­lete, re­placed by the math­ptmx pack­age, which sup­ports Times Ro­man text and (mostly) match­ing math­e­mat­ics. 

https://www.ctan.org/pkg/mathptmx
>this pack­age de­fines Adobe Times Ro­man (or equiv­a­lent) as de­fault text font . It su­per­sedes both the orig­i­nal times and the math­ptm pack­ages.

Zudem macht dies den Eintrag \fontfamily{ptm}\selectfont Überflüssig, da dies schon der Default wert ist.
Schadt natürlich nicht. Lasse ich auch drin.

Gruß Freddy

**Comment by andygrunwald** [comment]
Wenn du die Änderung machst, würde ich empfehlen, dass du die Sachen die obsolete sind, direkt entfernst. Es hat keinen Vorteil, wenn wir das ganze drin lassen.
