### ISSUE TITLE
Meta Informationen (Autor, Titel) mit Paket hyperref hinzufügen

### ISSUE THREAD

**Issue by jumpRun** [andygrunwald/FOM-LaTeX-Template#56]
![pdf_eigenschaften1](https://cloud.githubusercontent.com/assets/22481288/20859412/d18f7696-b95e-11e6-836a-c3a98de1c896.JPG)
![pdf_eigenschaften2](https://cloud.githubusercontent.com/assets/22481288/20859413/d1bdb614-b95e-11e6-9506-1c4df4116bb5.JPG)

Hey,

Meta Informationen bzw. Eigenschaften zum PDF Dokument hinzufügen.
Das Paket hyperref ist bereits eingebunden.

- [ ] In thesis_main.tex folgenden Code ergänzen.

`%-----------------------------------
% Meta informationen
%-----------------------------------
\input{skripte/meta}

\hypersetup{
	pdfinfo={
		Title={\myTitel},
		Subject={\myStudiengang},
		Author={\myAutor},
		Build=1.1
		% ...
	}
}`

gruß Freddy

PS: sobald ich mit allem mal durch bin, werde ich mal einen Pull Request versuchen. Hab das aber noch nie gemacht. Bis dahin lege ich erstmal die Issues an, damit die Infos nicht verloren gehen.

**Comment by andygrunwald** [comment]
Danke. Das ist eine gute Idee.
Ich warte mal deinen Pull Request ab. Wenn du das noch nie gemacht hast, empfehle ich dir folgendes zu lesen: [About pull requests](https://help.github.com/articles/about-pull-requests/)
