### ISSUE TITLE
Package inputenc Error: Unicode char ´ (U+B4)(inputenc) not set up for use with LaTeX. ...,heading=subbibliography,title={Bücher}]

### ISSUE THREAD

**Issue by normanmerten** [andygrunwald/FOM-LaTeX-Template#65]
Hallo,

ich habe eine Problem mit der Kompilierung. Mein Literaturverzeichnis erstelle ich per Citavi. Wenn ich das Literaturverzeichnis auskommentiere und dann kompiliere entsteht der Fehler nicht. Wenn ich allerdings das Literaturverzeichnis andrucken lassen möchte, kommt der o. g. Output.

Das Literaturverzeichnis habe ich nach dem o. g. Sonderzeichen durchsucht und einige gefunden. Diese habe ich in Citavi geändert, erneut exportiert und per Texteditor kontrolliert. Dort ist alles chiko. Ich bin ehrlich gesagt gerade etwas verzweifelt.

Könnt ihr mir helfen?

Viele Grüße

Norman

**Comment by normanmerten** [comment]
Ok, das Thema hat sich schon erledigt. In dem Literatur-Verzeichnis waren Untertitel die eckige Klammern hat. Das war vermutlich die Ursache für den Abbruch. Nun funktioniert alles.

**Comment by andygrunwald** [comment]
Freut mich, dass du es lösen konntest
