### ISSUE TITLE
Harvard Zitierstil

### ISSUE THREAD

**Issue by Gruhlfire** [andygrunwald/FOM-LaTeX-Template#66]
Hey Leute, 

Ich bin gerade im ersten Semester des MBA und will für meine folgenden 15 Studienarbeiten LaTeX nutzen. 2 habe ich bisher ohne geschrieben, da es Gruppenarbeiten waren. Für meine Arbeiten und später für meine Thesis möchte ich aber auf LaTeX zurückgreifen. Leider bin ich allerdings mangels Zeit nie über den LaTeX Anfänger Status hinausgekommen. :-/
Aktuell ist der Zitierstil ja als Fußnote hinterlegt. Was muss ich denn an der Vorlage ändern, damit der Harvard Stil angewendet wird? Beispiel: "(Autor, 2017)" (Autornachname, Jahr) 
Das Literaturverzeichnis muss entsprechend auch angelegt sein. Kann mir da zufällig jemand weiterhelfen?

Aktuell arbeite ich mit TexStudio, allerdings habe ich es noch nicht geschafft das richtig zu konfigurieren.

Vielen Dank für eure Hilfe und viele Grüße
Gruhl

**Comment by andygrunwald** [comment]
Hallo @Gruhlfire,

die Vorlage wurde zu einem Zeitpunkt erstellt, als noch die gekürzte Harvard Zitierweise angefordert wurde.
Bei deinen Anforderungen könnte ggf. folgender Link helfen: https://tex.stackexchange.com/questions/39454/how-do-i-use-the-harvard-citation-style

TexStudio hat erstmal nichts mit der Zitierweise an sich zu tun.

**Comment by Alf-R** [comment]
Hallo Andi,
habe gerade MiKTeX 2.9 herunter geladen und installiert.
Möchte meine ersten Semester- Arbeiten mit deinem Template erstellen.
Allerdings bekomme ich einige Fehlermeldungen (siehe Anhang), die ich nicht beheben kann.
Kannst du mir einen Tipp geben, was ich ändern muß?
Danke und Gruß
Alf

[log.txt](https://github.com/andygrunwald/FOM-LaTeX-Template/files/1351855/log.txt)

[thesis_main.blg.txt](https://github.com/andygrunwald/FOM-LaTeX-Template/files/1351865/thesis_main.blg.txt)

[thesis_main.log](https://github.com/andygrunwald/FOM-LaTeX-Template/files/1351861/thesis_main.log)

**Comment by andygrunwald** [comment]
Kein Feedback seit ~2 Monaten.
Ich schließe das ganze mal. Wenn das Problem nicht gelöst ist, bitte eröffne das Ticket wieder
