### ISSUE TITLE
Fehler beim FOM-LaTeX-Template kompilieren

### ISSUE THREAD

**Issue by Alf-R** [andygrunwald/FOM-LaTeX-Template#67]
Hallo Andi,
habe gerade MiKTeX 2.9 herunter geladen und installiert.
Möchte meine ersten Semester- Arbeiten mit deinem Template erstellen.
Allerdings bekomme ich einige Fehlermeldungen (siehe Anhang), die ich nicht beheben kann.
Kannst du mir einen Tipp geben, was ich ändern muß?
Danke und Gruß
Alf

[log.txt](https://github.com/andygrunwald/FOM-LaTeX-Template/files/1364550/log.txt)
[thesis_main.log](https://github.com/andygrunwald/FOM-LaTeX-Template/files/1364548/thesis_main.log)
[thesis_main.blg.txt](https://github.com/andygrunwald/FOM-LaTeX-Template/files/1364549/thesis_main.blg.txt)

**Comment by teiling88** [comment]
Bei mir hat der docker container am besten funktioniert.

**Comment by andygrunwald** [comment]
@Alf-R Wie @teiling88 bereits sagte, der Docker-Container funktioniert recht gut.
Der wurde speziell mit dem Ziel erstellt, um solche System-Bedingten Fehler auszuschließen.

Einige der Libraries im LaTeX-Umfeld haben breaking changes innerhalb von Releases.
Deswegen ist es wichtig, dass man genau die richtigen Versionen installiert hat. Ansonsten kann es zu den dir beschriebenen Fehlern kommen.

Probier doch mal bitte den Docker-Container aus. Ggf. hilft er dir.

**Comment by Alf-R** [comment]
Hi Andi,
habe den Docker installiert.
Auf dem 1. Rechner Windoof 10 lief der Docker nicht, auf dem 2. Rechner Windoof 10 lief er.
Habe eingetippt:
docker run -it --rm -v ${PWD}:/data/FOM-LaTeX-Template
--> also 1:1 nach deiner Vorgabe.
Das komplette Template steht in c:\data\FOM-LaTeX-Template
Fehlermeldung:
"docker run" requires at least 1 argument
Was soll ich anders machen?

**Comment by andygrunwald** [comment]
Bei Windows wird anscheinend die Variable `${PWD}` nicht aufgelöst.
Bitte ersetze `${PWD}` mit `c:\data\FOM-LaTeX-Template` und probiere es erneut.
Leider habe ich zur Zeit keinen Rechner mit Windows, auf dem ich das ganze testen könnte.

**Comment by andygrunwald** [comment]
@Alf-R Hast du es inzwischen zum laufen gebracht? Wenn ja, könntest du das ggf. in die README beisteuern für andere Windows-User?

**Comment by andygrunwald** [comment]
Siehe #80 für die Lösung.
