### ISSUE TITLE
Glossar fehlt

### ISSUE THREAD

**Issue by markuspoerschke** [andygrunwald/FOM-LaTeX-Template#7]
Ich werde für meine Arbeit ein Glossar benötigen. Hier wäre ein Beispiel für ein Glossar sehr hilfreich!

**Comment by andygrunwald** [comment]
Aktuell ist kein Glossar vorgesehen.
Ein Abkürzungsverzeichnis ist bereits vorhanden.

@ab04062008 war so lieb und hat dir ein Link gegeben, wie du ein Glossar einbauen kannst.
@markuspoerschke Ich hoffe das hilft dir :)

Wenn du es erfolgreich eingebunden hast, kannst du es gerne als Pull Request zur Verfügung stellen. Danke dir
