### ISSUE TITLE
Sections, Subsections etc. in Times und Fett

### ISSUE THREAD

**Issue by kigger88** [andygrunwald/FOM-LaTeX-Template#70]
Hallo zusammen,

wie kann ich die Überschriften in Times und Fett einstellen?
Probiert habe ich \setkomafont{disposition}{\normalfont\bfseries}     %Überschriften normal, fett

Problem: Im Inhaltsverzeichnis ist die erste Ebene jetzt auch fett dargestellt.

Danke & Grüße
kigger

**Comment by andygrunwald** [comment]
Hey @kigger88,

du könntest `\titleformat` nutzen.
Siehe hier: https://tex.stackexchange.com/questions/1455/how-to-set-the-font-for-a-section-title-and-chapter-etc

**Comment by andygrunwald** [comment]
@kigger88 Hast du es inzwischen zum laufen gebracht?

**Comment by andygrunwald** [comment]
Ich schließe dieses Ticket mal, weil es seit mehreren Monat keine Response von @kigger88 kam.
Wenn doch noch was kommt, einfach posten.
