### ISSUE TITLE
Mehrere Referenzen pro Seite auf eine Quelle in einer Fußnote

### ISSUE THREAD

**Issue by georg90** [andygrunwald/FOM-LaTeX-Template#73]
Moin!

Ich suche eine Möglichkeit mehrere Referenzen auf die gleiche Quelle in einer Fußnote zusammenzufassen, so dass das hier:

![image](https://user-images.githubusercontent.com/6489464/32697807-19080c2e-c799-11e7-8565-4ce37f5363df.png)

zu so etwas wird:

¹ ² Fischer(o.J.)

Jemand eine Idee? Evtl. durch ein Komma getrennt?

**Comment by koep** [comment]
Hallo @georg90 ,

schau mal hier: #33

**Comment by georg90** [comment]
Hi @koep 
Danke für die schnelle Rückmeldung. Hatte ich gesehen, finde ich aber (gerade im Verlauf einer Thesis) eher unglücklich, da man nach jeder Einfügung einer neuen Quelle, alle nachfolgenden anpassen muss (dafür nutzen wir ja erst Referenzen, damit diese sich automatisch anpassen)..

Ich meine es gab da ein Package, aber alles wa sich online finde, passt nicht wirklich wie ich mir das vorstelle. Leider verlangt die FOM das ja mittlerweile bei Fußnotenzitaten

**Comment by andygrunwald** [comment]
@georg90 Wenn du eine Lösung gefunden hast, würde ich mich über ein PR freuen (auch wenn es nur ein neuer Absatz in der README ist). Das hilft zukünftigen Studenden ggf. auch

**Comment by andygrunwald** [comment]
@georg90 Hast du es inzwischen zum laufen gebracht? Wenn ja, kannst du kurz beschreiben was und wie du gemacht hast?
Ggf. können wir das in die README integrieren und somit an andere Nutzer zurück spielen

**Comment by georg90** [comment]
nope :-( Bitte immernoch um Hilfe

**Comment by andygrunwald** [comment]
@georg90 Hilft dir das hier weiter? [Reference different places to the same footnote](https://tex.stackexchange.com/questions/35043/reference-different-places-to-the-same-footnote)?

**Comment by andygrunwald** [comment]
Ich schließe dieses Ticket mal, weil es seit mehreren Monat keine Response von @georg90  kam.
Wenn doch noch was kommt, einfach posten.

**Comment by georg90** [comment]
Ja @andygrunwald Problem besteht weiterhin ;-) Ich wollte nicht einfach ein "Nein" zurückmelden.

Lösungen sind weiter sehr willkommen

**Comment by dhd80** [comment]
Hi @georg90,

wäre es ggf. sinnvoller "ebd.", also "ebenda" einzubinden? "ibidem"
\DefineBibliographyStrings{german}{ibidem = {ibid\adddot}}
Bsp. ist von:
https://golatex.de/ibid-statt-ebd-biblatex-authoryear-ibid-t18976.html

VG

**Comment by andygrunwald** [comment]
Hey @georg90,
gibt es hier inzwischen eine Lösung? Bzw. hast du einen Weg gefunden und kannst diesen mit uns teilen? Danke dir.

**Comment by ChristianLuxem** [comment]
Hallo zusammen, 
gibt es hier einen neuen Status? Sonst würde ich das Ticket gerne schließen.

**Comment by georg90** [comment]
Habe es manuell gemacht für meine Thesis.. Kann zu, ist aber nicht geöst.
