### ISSUE TITLE
"Style" des Literaturverzeichnisses

### ISSUE THREAD

**Issue by lifeofpablo** [andygrunwald/FOM-LaTeX-Template#77]
Hallo Andy,

ich bein gerade fleißig dabei, meine Bachelor-Thesis zu schreiben. 
Nun hat mein Prof die angemerkt, dass ihm die Art des Literaturverzeichnisses nicht wirklich zusagt, da sich die Einträge nur relativ umständlich den Fußnoten zuordnen lassen.

Das Template verwendet ja das Paket biblatex mit dem Style "numeric" und als citestyle "authoryear". Nun ist leider gerade der style numeric unglücklich, da damit einfach nur die Einträge hochgezählt werden. Mein Prof hat dadurch Probleme, die Fußnoten eindeutig den jeweiligen Stellen im Verzeichnis zuzuordnen. 

## Ist-Verzeichnis

![ist-verzeichnis](https://user-images.githubusercontent.com/34478418/33884970-0d4cb072-df42-11e7-89b8-5a4f44393d7c.png)

## Ist-Fußzeile

![ist-fusszeile](https://user-images.githubusercontent.com/34478418/33884971-0d674fae-df42-11e7-86fe-d1612416b09d.png)

## Soll-Verzeichnis

![soll-verzeichnis](https://user-images.githubusercontent.com/34478418/33884972-0d80cdbc-df42-11e7-9bcb-905c269cbaa0.png)

Ich habe mal drei Bilder eingefügt. Ideal wäre das Verzeichnis wie auf dem Bild "soll-verzeichnis"
Ich habe bereits einige styles ausprobiert, leider ohne Erfolg.

Kannst du an der Stelle vielleicht helfen?

Danke und Grüße,
Philip

**Comment by andygrunwald** [comment]
Hey Philip / @lifeofpablo,

die Art und Weise wie das Literatur-Verzeichnis aufgebaut wurde, war zu meiner Zeit der Standard von der FOM, der Pflicht war. Ich weiß leider nicht ob sich dieser geändert hat, da ich nicht mehr studiere.

Bei der Anpassung kann ich dir gerade leider nicht helfen. Ich habe mich zu meiner Zeit auch recht viel mit Google beholfen und habe dadurch LaTeX gelernt.
Schau doch mal was du da findet und wenn du weiter kommst, schreib doch mal hier rein was du für Anpassungen gemacht hast.
Ggf. können andere Leute, die ebenfalls in deiner Lage sind, davon auch profitieren.

Viel Erfolg bei deiner Arbeit.

**Comment by andygrunwald** [comment]
Ich schließe dieses Ticket mal, weil es seit mehreren Monat keine Response von @lifeofpablo kam.
Wenn doch noch was kommt, einfach posten.

**Comment by lifeofpablo** [comment]
Hi Andy,

hatte das Ticket hier komplett aus den Augen verloren. Ich konnte das Problem leider auch nicht wirklich lösen. Ich konnte mich mit meinem Prof auf einen anderen Zitierstil einigen, den ich dann einfach über die thesis_main unter citystyle geändert habe. Die Arbeit war dennoch erfolgreich.

Grüße,
Philip

**Comment by andygrunwald** [comment]
Danke fürs Feedback. Und das freut mich, das die Arbeit ein Erfolg war :)
