### ISSUE TITLE
Unterschiedliche Schriftarten durch pdflatex

### ISSUE THREAD

**Issue by neikei** [andygrunwald/FOM-LaTeX-Template#84]
Zu allererst, vielen Dank für das Template! Es ist eine tolle Vorlage und erleichtert den Einstieg in LaTeX sehr.  👍 

Mir sind die unterschiedlichen Schriftarten aufgefallen, die z.B. auf dem Deckblatt und im Fließtext verwendet werden, jedoch nicht für Überschriften. Dies scheint an dem default font von pdflatex zu liegen und lässt sich mit den folgenden Zeilen ganz einfach in die Schriftart "helvet" ändern, die zumindest meinem Eindruck nach auch für die serifenlosen Überschriften verwendet wird. 

```
\usepackage[scaled]{helvet}
\renewcommand\familydefault{\sfdefault}
```

--
Hier ein [Beispiel](https://github.com/neikei/FOM-LaTeX-Template/blob/master/thesis_main.pdf). Ich habe jedoch so viele Anpassungen speziell für Ubuntu in meinem Fork, da macht ein PR wenig Sinn. 🤦‍♂️

**Comment by andygrunwald** [comment]
Hey @neikei,

danke!
Wenn du soviele Änderungen hast, aber den Tipp dennoch anderen Leuten zur Verfügung stellen möchtest, kannst du gerne einen PR mit dem Code in der README beschreiben.
Dort haben wir schon verschiedene Bereiche zB [Quellcode einbinden](https://github.com/andygrunwald/FOM-LaTeX-Template#quellcode-einbinden).
Wäre das eine Möglichkeit?

**Comment by neikei** [comment]
Danke für den Tipp! Mir war bisher nicht bewusst, dass ich trotz eines existierenden Forks auf Github einzelne Dateien modifizieren und dazu PRs erstellen kann.

**Comment by andygrunwald** [comment]
Closed via https://github.com/andygrunwald/FOM-LaTeX-Template/pull/85
