### ISSUE TITLE
Überschriften extrem pixelig

### ISSUE THREAD

**Issue by dklinger** [andygrunwald/FOM-LaTeX-Template#91]
Hallo,
weiß jemand wieso die Überschriften beim zoomen so extrem pixelig sind? Ich habe das Template früher schon mal für eine Semesterarbeit verwendet und nutze es gerade in der aktuellen Version für die Bachelorarbeit. In der alten Version ist das definitiv nicht so, da sieht alles smooth aus.
Beste Grüße,
Daniel

**Comment by andygrunwald** [comment]
Hast du ggf. mal zwei PDFs zum Vergleich?
Von wann ist deine Semesterarbeit? Weil dann können wir ggf. sehen, welche Änderungen in der Zeit reingeflossen sind und den richtigen Commit ermitteln.

**Comment by dklinger** [comment]
Hab die Codezeile schon gefunden. Das hinzufügen von \usepackage{times} behebt die pixeligen Überschriften. Zwar bin ich mir nicht sicher inwiefern es noch weiteren Einfluss auf das Aussehen hat aber das ich das Package schon bei anderen Arbeiten der FOM verwendet habe, sollte das schon passen.

**Comment by andygrunwald** [comment]
@dklinger Kannst du dafür einen PR machen?
Ich denke, dass diese Modifikation enigen Leuten helfen könnte

**Comment by daneb255** [comment]
Bitte aber vorher diesen Artikel durchlesen:

https://latex-kurs.de/fragen/schriftarten/Times_New_Roman.html

> Eingebunden wird die Schriftart über das bereits erwähnte mathptmx Paket. Es existiert zwar auch ein times Paket, aber von dessen Verwendung wird im Allgemeinen abgeraten. Da es nicht nur die Serifen Schriftart, sondern auch die serifenlose Schrift und Schreibmaschinenschrift neu setzt. Dabei wird aber die serifenlose Schrift Helvetica nicht an Times angepasst und keine passende Mathematikschrift eingebunden

**Comment by dklinger** [comment]
Also bei mir siehts tatsächlich so aus:
![image](https://user-images.githubusercontent.com/2249766/39664820-d29e17e0-5089-11e8-80ab-094c11cb7fce.png)

Danke für den Link. Habe das times-packages jetzt wieder rausgeworfen und verwende die dort angegebene Variante mit Helvetica und Courier:
\usepackage[scaled=0.9]{helvet}
\usepackage{courier}
Dadurch sieht das ganze, ähnlich wie mit dem times-Package, schon wesentlich besser aus:
![image](https://user-images.githubusercontent.com/2249766/39664834-1b2bdd6c-508a-11e8-9485-51a93a2b52a7.png)

Wieso es bei dir nicht nachvollziehbar ist, ist eine gute Frage. Ich habe mir gerade extra nochmal den unveränderten master-Stand des Repositories geholt, dort sieht es nach einem durchgeführten Build 1:1 aus wie mein Pixel-Beispiel von oben.
Werde auf jeden Fall mal einen PR erstellen.

**Comment by andygrunwald** [comment]
@dklinger @daneb255 Könnt ihr mal eure genauen LaTeX-Versionen posten + OS und Co?
Oder kompiliert ihr beide eure Dokumente mit dem Docker-File?
Ich hab das Gefühl, dass sich hier die Versionen unterscheiden.

**Comment by fomdane** [comment]
Ich habe texlive 2018 und kompiliere mit dem Shell Skript

Viele Grüße

Daniel Bitzer
Von meinem iPhone gesendet
________________________________

**Comment by daneb255** [comment]
Ich benutze texlive 2018 und kompiliere mit dem Shell Skript

**Comment by dklinger** [comment]
Ich habe Windows 10, TeXstudio 2.12.8 und MiKTeX 2.9 im Einsatz.

**Comment by andygrunwald** [comment]
Hey @dklinger,

hast d inzwischen eine Lösung gefunden? Oder einen Workaround, den du mit uns teilen kannst?
Gerade wurde auf TeX 2018 geupdated. Ggf. kannst du es damit erneut probieren?
Eine Rückmeldung würde mich freuen.

**Comment by ChristianLuxem** [comment]
Da hier keine Rückmeldung mehr kommt, schließe ich das Ticket. Sollte der Fehler weiterhin auftreten, bitte kurz schreiben, dann öffnen wir wieder. Durch die Umstellung auf Docker und sonstige Änderungen an der Schriftart und ähnliches, halte ich es aber für unwahrscheinlich, dass der Fehler noch reproduzierbar ist.
