### ISSUE TITLE
Hängender Einzug ab 2. Zeile bei Referenzen in der .bib Datei

### ISSUE THREAD

**Issue by SaunameisterSven** [andygrunwald/FOM-LaTeX-Template#96]
Hallo zusammen, 
ich nutze die Vorlage einwandfrei mit kleineren Änderungen.
Allerdings scheite ich leider daran für das Literaturverzeichnis einen Einzug ab der 2. Zeile einzubinden.
Ich habe nun 2 Tage das Internet durchforstet und nach Lösungen gesucht, aber jeder Versuch scheiterte.

Jede Kompilierung sieht am Ende standardmäßig wie folgt aus:
![lit-beispiel](https://user-images.githubusercontent.com/40333988/41506851-f340951e-7225-11e8-976a-0535f7ecd94d.JPG)

Ich würde mich über eine schnelle Hilfe sehr freuen. Danke und LG :)

**Comment by andygrunwald** [comment]
Hey @SaunameisterSven,

das Problem ist, dass Modifikationen auch das Literatur-Verzeichnis modifiziert haben.
Deswegen ist es recht schwer, das ganze ohne nähere Kenntnis zu Lösen.
Die meisten LaTeX-Foren fordern ein Minimal-Exampel.

Ich kenne die Lösung leider gerade nicht. Ist dies eine Anforderung der FOM?

**Comment by dhd80** [comment]
Hi @SaunameisterSven,

probier mal einen andere Bibtex bibliography style einzubinden, hier eine Liste:
https://www.sharelatex.com/learn/latex/Bibtex_bibliography_styles
Ansonsten wäre hier die Lösung mit Tex Anpassungen:
https://tex.stackexchange.com/questions/51294/indent-second-line-of-a-bibliography

VG

**Comment by andygrunwald** [comment]
Hey @SaunameisterSven,

hast du inzwsichen eine Lösung für deine Frage gefunden? Oder einen Workaround, den du mit uns teilen kannst? Das wäre Klasse. So könnten mehr Leute davon profitieren.

**Comment by SaunameisterSven** [comment]
Hey @andygrunwald 

für die Hausarbeit habe ich mir das Quellenverzeichnis am Ende extern erstellt und als Bild eingebunden.
Da ich für die Thesis aber eine PDF-Version abgeben muss, in der auch das Quellenverzeichnis von der Suchfunktion erkannt wird, musste ich mich für die Thesis leider für Word entscheiden. Schade, dass es an dieser kleinen Kinke gescheitert ist. Ich habe demnach keine Lösung mehr gefunden gehabt.

Beste Grüße!

**Comment by andygrunwald** [comment]
Danke fürs feedback. So wie ich das rauslese,hast du es dennoch geschafft. Gratulation.
Ich würde dieses Ticket erstmal auflassen. Vielleicht hat jemand ja eine Lösung.

**Comment by SimonHaak** [comment]
Hi @andygrunwald 
Das Ticket müsstest du eigentlich schließen können.
Wirf mal einen Blick in die aktuelle PDF im Master Branch ;)

Da wurde mit \bibhang{1cm} der Zeileneinzug eingebaut.

**Comment by andygrunwald** [comment]
Mach ich. Danke.
